from openpyxl import Workbook
from openpyxl.styles import (
    Font, PatternFill, Alignment, Border, Side, GradientFill
)
from openpyxl.utils import get_column_letter

wb = Workbook()
wb.remove(wb.active)  # remove default sheet

# ── Palette ────────────────────────────────────────────────────────────────
CATS = {
    "HTML":          {"color": "E34C26", "light": "FDE8E2", "icon": "🌐"},
    "CSS":           {"color": "264DE4", "light": "E2E8FD", "icon": "🎨"},
    "JavaScript":    {"color": "F7DF1E", "light": "FEFBE0", "icon": "⚡"},
    "TypeScript":    {"color": "3178C6", "light": "E0EAF8", "icon": "🔷"},
    "React":         {"color": "61DAFB", "light": "E0F8FD", "icon": "⚛️"},
    "React Native":  {"color": "20232A", "light": "E8E9EA", "icon": "📱"},
    "Next.js":       {"color": "000000", "light": "E8E8E8", "icon": "▲"},
}

DIFF_COLORS = {
    "Basic":        "C6EFCE",
    "Intermediate": "FFEB9C",
    "Advanced":     "FFC7CE",
    "Tricky":       "E6B3FF",
}

WHITE = "FFFFFF"
HEADER_BG = "1E293B"

thin = Side(style="thin", color="D1D5DB")
border = Border(left=thin, right=thin, top=thin, bottom=thin)


def hdr(color):
    return PatternFill("solid", start_color=color, end_color=color)


def bold_font(size=11, color="000000", white=False):
    return Font(name="Arial", bold=True, size=size, color="FFFFFF" if white else color)


def reg_font(size=10, color="1E293B"):
    return Font(name="Arial", size=size, color=color)


# ── Data ───────────────────────────────────────────────────────────────────
# Columns: Topic, Subtopic, Difficulty, Key Concept, Tricky Interview Question, Answer/Explanation, Code Snippet

DATA = {
"HTML": [
  # Basic
  ("Document Structure","DOCTYPE & HTML5","Basic","DOCTYPE declaration tells browser the HTML version","What happens if you omit <!DOCTYPE html>?","Browser enters quirks mode — it mimics old, inconsistent rendering behaviour of IE5/Netscape. Layout calculations differ, box model changes.","<!-- Always first line -->\n<!DOCTYPE html>\n<html lang='en'>\n<head><meta charset='UTF-8'></head>\n<body></body></html>"),
  ("Document Structure","head vs body","Basic","<head> contains metadata; <body> contains content","What goes in <head> that affects rendering performance?","<link rel=stylesheet> blocks rendering. Scripts with no defer/async also block. Meta charset must be in first 1024 bytes.","<head>\n  <meta charset='UTF-8'>\n  <meta name='viewport' content='width=device-width'>\n  <link rel='stylesheet' href='style.css'>\n  <title>Page</title>\n</head>"),
  ("Semantics","Semantic HTML5 elements","Basic","Elements that convey meaning: article, section, nav, aside, header, footer, main","Why use semantic HTML instead of divs everywhere?","Improves accessibility (screen readers), SEO (crawlers understand structure), maintainability, and enables browser default styling/behaviour.","<main>\n  <article>\n    <header><h1>Title</h1></header>\n    <section>Content</section>\n    <footer>Author</footer>\n  </article>\n  <aside>Sidebar</aside>\n</main>"),
  ("Semantics","figure & figcaption","Basic","Groups media with its caption","Can a figure contain multiple images?","Yes — figure is a content unit. One figcaption describes all children. Use multiple figures for separate captioned items.","<figure>\n  <img src='a.jpg' alt='Chart showing revenue'>\n  <figcaption>Q4 Revenue</figcaption>\n</figure>"),
  ("Forms","Form elements","Basic","input, select, textarea, button, label, fieldset, legend","What's the difference between button type=submit vs type=button?","type=submit submits the nearest form (default type inside a form). type=button does nothing by default — needs JS. Omitting type inside a form defaults to submit.","<form action='/submit' method='POST'>\n  <label for='name'>Name</label>\n  <input id='name' name='name' required>\n  <button type='submit'>Send</button>\n</form>"),
  ("Forms","Input types & validation","Basic","email, number, date, range, file — browser-native validation","Does required prevent form submission in all browsers?","No. It triggers browser native validation UI but can be bypassed with formnovalidate or JS submission. Server-side validation is mandatory.","<input type='email' required pattern='.+@.+\..+'>\n<input type='number' min='1' max='100' step='1'>"),
  ("Accessibility","ARIA roles & attributes","Intermediate","aria-label, aria-labelledby, aria-describedby, role","When should you NOT use ARIA?","When native HTML semantics already provide the meaning. First rule of ARIA: don't use it if a native element exists. aria-label on a <button> can override its text — screen reader reads the label, not the visible text.","<button aria-label='Close dialog' aria-expanded='false'>\n  <svg aria-hidden='true'>...</svg>\n</button>"),
  ("Accessibility","tabindex","Intermediate","Controls keyboard focus order","What does tabindex=-1 do?","Makes element programmatically focusable (via .focus() in JS) but removes it from the tab order. Used for modal dialogs — focus trap without cluttering the default flow.","<!-- In tab order -->\n<div tabindex='0' role='button'>Click</div>\n<!-- Only via JS -->\n<div tabindex='-1' id='modal'>Modal</div>"),
  ("Accessibility","alt text rules","Intermediate","Alt text describes image purpose, not appearance","When should alt be empty string?","Decorative images: alt='' tells screen readers to skip. Never omit alt entirely — screen readers fall back to the file name which is noisy.","<img src='logo.svg' alt='Acme Corp'>\n<!-- decorative -->\n<img src='divider.png' alt=''>"),
  ("Metadata","meta tags","Basic","Viewport, charset, og:, twitter: cards","What does content='width=device-width,initial-scale=1' actually do?","width=device-width sets layout viewport = device screen width. initial-scale=1 prevents automatic zoom. Without it, mobile browsers zoom out to fit 980px desktop viewport.","<meta name='viewport' content='width=device-width, initial-scale=1'>\n<meta property='og:title' content='My App'>\n<meta name='description' content='150 char description'>"),
  ("Performance","Resource hints","Intermediate","preload, prefetch, preconnect, dns-prefetch","Difference between preload and prefetch?","preload: high priority, needed for current page (fonts, critical CSS). prefetch: low priority, likely needed on next page. Wrong preload wastes bandwidth for mobile users.","<link rel='preconnect' href='https://fonts.googleapis.com'>\n<link rel='preload' href='font.woff2' as='font' crossorigin>\n<link rel='prefetch' href='/next-page.js'>"),
  ("Performance","defer vs async","Intermediate","Controls when script downloads and executes","What's the execution order with multiple defer scripts?","defer scripts execute in document order after DOM is parsed, before DOMContentLoaded. async executes as soon as downloaded — order not guaranteed. Use defer for most scripts; async for independent analytics.","<!-- Guaranteed order -->\n<script defer src='a.js'></script>\n<script defer src='b.js'></script>\n<!-- Random order -->\n<script async src='analytics.js'></script>"),
  ("Media","picture element","Intermediate","Art direction and format negotiation","How does browser choose between source elements?","Evaluates source elements top-to-bottom, picks first where media query matches AND type is supported. Falls back to img src. Order matters!","<picture>\n  <source media='(min-width:800px)' srcset='wide.webp' type='image/webp'>\n  <source media='(min-width:800px)' srcset='wide.jpg'>\n  <img src='narrow.jpg' alt='Product'>\n</picture>"),
  ("Media","video & audio","Basic","HTML5 native media elements","How do you prevent layout shift when video loads?","Set explicit width/height attributes (or CSS aspect-ratio). Without dimensions, browser allocates 0 height until metadata loads, causing CLS.","<video width='640' height='360' controls preload='metadata'>\n  <source src='video.webp' type='video/webm'>\n  <source src='video.mp4' type='video/mp4'>\n</video>"),
  ("Tables","Accessible tables","Intermediate","thead, tbody, tfoot, th scope, caption","What is scope attribute on th?","scope='col' links header to entire column; scope='row' links to entire row. Without scope, screen readers may not associate headers correctly with data cells.","<table>\n  <caption>Sales Data</caption>\n  <thead>\n    <tr><th scope='col'>Month</th><th scope='col'>Revenue</th></tr>\n  </thead>\n  <tbody><tr><td>Jan</td><td>$10k</td></tr></tbody>\n</table>"),
  ("Shadow DOM","Web Components","Advanced","Custom elements, Shadow DOM, HTML templates","What is Shadow DOM piercing and why was it removed?","::shadow and /deep/ selectors allowed external CSS to pierce shadow boundaries. Removed in Chrome 63 because they broke encapsulation — the whole point of Shadow DOM.","class MyBtn extends HTMLElement {\n  constructor() {\n    super();\n    const shadow = this.attachShadow({mode: 'open'});\n    shadow.innerHTML = `<button><slot></slot></button>`;\n  }\n}\ncustomElements.define('my-btn', MyBtn);"),
  ("Shadow DOM","Open vs Closed shadow","Advanced","mode:'open' exposes shadowRoot, mode:'closed' hides it","Can you access a closed shadow root?","Not via element.shadowRoot (returns null). But the reference returned by attachShadow({mode:'closed'}) can be stored and used — so 'closed' is security-by-obscurity, not true isolation.","const shadow = el.attachShadow({mode: 'closed'});\nconsole.log(el.shadowRoot); // null\n// But shadow variable still works"),
  ("Scripting","data attributes","Basic","data-* attributes for custom metadata","Are data attributes accessible to CSS?","Yes via attribute selector [data-state='active'] and var()  indirection via CSS custom properties set from JS. Not the same as content — don't put visible text only in data attributes.","<!-- HTML -->\n<div data-user-id='42' data-role='admin'></div>\n\n<!-- CSS -->\n[data-role='admin'] { border: 2px solid gold; }\n\n// JS\nel.dataset.userId // '42'"),
  ("Scripting","contenteditable","Intermediate","Makes element editable inline","What are the pitfalls of contenteditable?","Different browsers insert different HTML on Enter (div vs p vs br). Pasting rich text injects arbitrary HTML. Need to sanitize. Not ideal for rich editors — use libraries.","<div contenteditable='true' role='textbox' aria-multiline='true'\n  aria-label='Edit comment'>\n  Type here...\n</div>"),
  ("Tricky","void elements","Tricky","Self-closing elements with no content model","Why can't you write <script/> as a self-closing tag?","In HTML (not XHTML), only void elements are self-closing. <script/> is parsed as an open tag and everything after becomes its content, breaking the page. HTML5 parsers are forgiving but wrong output results.","<!-- CORRECT -->\n<br><img src='x.jpg' alt=''><input type='text'>\n<!-- WRONG (breaks page) -->\n<script src='app.js'/>"),
  ("Tricky","Inline vs block","Tricky","Inline elements can't contain block elements","What happens if you put a div inside a p?","The browser auto-closes the <p> before the <div>. The DOM differs from the source HTML. Inspecting with DevTools reveals the corrected tree.","<!-- Source -->\n<p>Text <div>block</div> more</p>\n<!-- DOM result -->\n<p>Text</p><div>block</div><p> more</p>"),
  ("Tricky","Boolean attributes","Tricky","Presence = true; absence = false","Does disabled='false' enable an element?","No! The mere presence of disabled disables it regardless of value. To enable, remove the attribute entirely. disabled='false' still disables.","<!-- BOTH disabled -->\n<input disabled>\n<input disabled='false'>\n<!-- enabled -->\n<input>"),
  ("Tricky","Link rel=noopener","Tricky","Security attribute for external links","Why add rel='noopener noreferrer' to target=_blank links?","Without noopener, the new tab gets window.opener reference to your page and can redirect it (reverse tabnapping attack). noreferrer also omits the Referer header.","<a href='https://external.com' target='_blank'\n  rel='noopener noreferrer'>External</a>"),
],

"CSS": [
  ("Box Model","Box sizing","Basic","content-box vs border-box","Why is box-sizing:border-box almost always better?","In content-box, padding and border add to declared width, making layout math complex. border-box includes them, making width the total element size — intuitive for grid/flex layouts.","*, *::before, *::after {\n  box-sizing: border-box;\n}"),
  ("Box Model","Margin collapsing","Tricky","Adjacent vertical margins merge into the larger one","Does margin collapsing happen with flexbox or grid children?","No. Collapsing only happens in normal flow (block formatting context). Flex/grid children never collapse margins with each other or their parent.","/* These margins collapse to 20px, not 30px */\n.a { margin-bottom: 20px; }\n.b { margin-top: 10px; }\n/* No collapse */\n.flex { display: flex; }  .flex > * { margin: 10px; }"),
  ("Specificity","Specificity calculation","Intermediate","(id, class/attr/pseudo-class, element) tuple","Which wins: #id .class or .a .b .c .d .e .f .g?","#id .class wins (1,1,0). No matter how many classes/elements you chain, they never exceed one ID in specificity. IDs are extremely specific.","/* Specificity (0,1,0) -- class */\n.btn { color: red; }\n/* Specificity (1,0,0) -- ID always wins */\n#submit { color: blue; }\n/* !important overrides all */\n.btn { color: green !important; }"),
  ("Specificity","!important cascade","Tricky","!important reverses specificity — lower spec !important beats higher spec normal","Does !important always win?","Not against another !important. If two !important declarations conflict, specificity decides between them. User agent !important styles also override author !important (for accessibility features like increased font size).","/* User stylesheet (accessibility) */\n* { font-size: 20px !important; }\n/* Author -- loses to user !important */\n.text { font-size: 14px !important; }"),
  ("Layout","Flexbox","Intermediate","1D layout: row or column","What does flex:1 actually set?","flex: 1 = flex-grow:1, flex-shrink:1, flex-basis:0. The 0 basis is key — items share space proportionally from 0, ignoring content size. flex:1 1 auto uses content size as starting point.","/* Equal width columns */\n.parent { display: flex; }\n.child { flex: 1; }\n/* Prevent shrinking below content */\n.no-shrink { flex-shrink: 0; }"),
  ("Layout","Grid","Intermediate","2D layout: rows and columns","What is the difference between auto-fill and auto-fit?","auto-fill creates as many tracks as will fit, leaving empty columns. auto-fit collapses empty tracks to 0, so items stretch to fill. Relevant when items < available columns.","/* auto-fit: items stretch to fill row */\n.grid {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));\n}"),
  ("Layout","Positioning","Intermediate","static, relative, absolute, fixed, sticky","When does position:sticky stop sticking?","When its scroll container (nearest overflow:scroll/auto ancestor) ends. Sticky is relative to that container, not the viewport. Common pitfall: overflow:hidden on a parent kills sticky.","/* Sticky header per section */\n.section-header {\n  position: sticky;\n  top: 0;\n  z-index: 10;\n  background: white;\n}"),
  ("Layout","z-index & stacking context","Tricky","Z-index only works within a stacking context","Why does a high z-index sometimes not work?","Child elements can't escape their parent's stacking context. If .parent has z-index:1, its child with z-index:9999 still loses to an element with z-index:2 outside the parent.","/* Stacking context created by: */\n/* position + z-index != auto */\n/* opacity < 1 */\n/* transform, filter, will-change */\n/* isolation: isolate */\n.isolate { isolation: isolate; }"),
  ("Selectors","Pseudo-classes","Intermediate","State-based selectors: :hover, :focus, :nth-child, :is, :where, :has","What is the difference between :nth-child and :nth-of-type?","nth-child counts all siblings regardless of type. nth-of-type counts only same-type siblings. p:nth-child(2) selects a p only if it's the 2nd child; p:nth-of-type(2) selects the 2nd p regardless of position.","/* 2nd child only if it's a p */\np:nth-child(2) { color: red; }\n/* 2nd p regardless of position */\np:nth-of-type(2) { color: blue; }\n/* :has (parent selector) */\n.card:has(img) { padding: 0; }"),
  ("Selectors","Pseudo-elements","Basic","::before, ::after, ::placeholder, ::selection","Can you add multiple ::before to an element?","No. An element has exactly one ::before and one ::after. Use the content property to compose text. For multiple decorative elements, nest real elements or use box-shadow to fake them.","/* Only one ::before per element */\n.badge::before {\n  content: '★';\n  color: gold;\n}\n/* Multi-shadow fake borders */\n.outline {\n  box-shadow: 0 0 0 2px red, 0 0 0 4px blue;\n}"),
  ("Typography","CSS custom properties","Intermediate","--var-name: value; consumed by var()","Can custom properties inherit?","Yes, they inherit by default. Set on :root to make global. Can be overridden per component. Cannot be set inside media queries on :root and expect inheritance to work differently — the value inherits as-is.","  :root {\n  --color-primary: #6366F1;\n  --spacing-base: 16px;\n}\n.btn {\n  background: var(--color-primary);\n  padding: var(--spacing-base);\n}\n.dark {\n  --color-primary: #818CF8;\n}"),
  ("Typography","Fluid typography","Advanced","clamp() for responsive type without breakpoints","What does clamp(min, preferred, max) return?","clamp returns preferred unless it's below min (returns min) or above max (returns max). Use vw as preferred for fluid scaling: clamp(1rem, 2.5vw, 2rem).","html {\n  font-size: clamp(14px, 1rem + 0.5vw, 18px);\n}\nh1 {\n  font-size: clamp(1.5rem, 5vw, 3rem);\n}"),
  ("Animation","Transitions","Basic","Smooth state changes","Which properties should you avoid transitioning for performance?","Avoid properties that trigger layout (width, height, top, margin) — cause reflow every frame. Prefer transform and opacity — composited by GPU, no layout/paint.","/* BAD: causes reflow */\n.bad { transition: width 0.3s, margin 0.3s; }\n/* GOOD: GPU composited */\n.good {\n  transition: transform 0.3s, opacity 0.3s;\n}\n.good:hover { transform: translateX(10px); }"),
  ("Animation","Keyframe animations","Intermediate","@keyframes with animation shorthand","What is will-change and when should you use it?","will-change hints to browser to promote element to its own compositor layer before animation starts, reducing jank. Use sparingly — every will-change element costs GPU memory. Apply only just before animation, remove after.","@keyframes slide {\n  from { transform: translateX(-100%); opacity: 0; }\n  to   { transform: translateX(0);    opacity: 1; }\n}\n.drawer {\n  animation: slide 0.3s ease-out;\n}"),
  ("Responsive","Media queries","Basic","@media rules for different viewports","What's the difference between min-width and max-width approaches?","min-width = mobile-first (start with mobile styles, add complexity for larger screens). max-width = desktop-first. Mobile-first generally produces smaller CSS and is recommended.","/* Mobile first */\n.nav { flex-direction: column; }\n@media (min-width: 768px) {\n  .nav { flex-direction: row; }\n}"),
  ("Responsive","Container queries","Advanced","@container — size relative to parent, not viewport","When do container queries outperform media queries?","When a component is reused in different layouts — sidebar vs main content. Media query sees viewport; container query sees the parent's available width. Component becomes truly self-contained.","@container (min-width: 600px) {\n  .card { display: grid; grid-template-columns: 1fr 2fr; }\n}\n.card-wrapper {\n  container-type: inline-size;\n}"),
  ("Performance","Critical CSS","Advanced","Inline above-fold CSS to unblock rendering","What is render-blocking CSS?","All <link rel=stylesheet> block rendering until downloaded & parsed. Solution: inline critical CSS in <style> tags, lazy-load the rest with preload trick.","<style>/* critical above-fold */</style>\n<link rel='preload' href='full.css' as='style'\n  onload='this.rel=\"stylesheet\"'>\n<noscript><link rel='stylesheet' href='full.css'></noscript>"),
  ("Tricky","inherit vs initial vs unset vs revert","Tricky","CSS keyword values","What does unset do?","unset = inherit if property is inheritable, initial if not. It's a smart reset. revert rolls back to browser's stylesheet default. all:unset resets all properties at once.","/* Reset everything to browser defaults */\n.unstyled { all: revert; }\n/* Smart unset */\n.clean { color: unset; /* inherits */ border: unset; /* initial */ }"),
  ("Tricky","Specificity of :is() and :where()","Tricky","Different specificity for similar selectors","What's the specificity of :where()?","Zero. :where() always has 0 specificity, making it easy to override. :is() takes the specificity of its most specific argument. :not() also takes the specificity of its argument.","/* Specificity = 0 -- easily overridden */\n:where(h1, h2, h3) { margin: 0; }\n/* Specificity = (0,0,1) from 'h1' */\n:is(h1, h2, h3) { margin: 0; }"),
  ("Tricky","CSS logical properties","Advanced","Inline/block instead of top/left/right/bottom","Why use margin-inline-start instead of margin-left?","Logical properties adapt to writing direction (LTR/RTL) and writing mode (horizontal/vertical). In RTL, margin-inline-start is on the right — no need for [dir=rtl] overrides.","/* Adapts to RTL automatically */\n.item {\n  margin-inline-start: 1rem;  /* left in LTR, right in RTL */\n  padding-block: 0.5rem;      /* top and bottom */\n  border-inline-end: 1px solid; /* right in LTR */\n}"),
],

"JavaScript": [
  ("Core","var vs let vs const","Basic","Scope, hoisting, re-assignment differences","What is the temporal dead zone?","The TDZ is the period between entering a block scope and the let/const declaration being reached. Accessing the variable throws ReferenceError — unlike var which returns undefined.","console.log(x); // ReferenceError (TDZ)\nlet x = 5;\n\nconsole.log(y); // undefined (hoisted)\nvar y = 5;"),
  ("Core","Closures","Intermediate","Function that retains access to its outer scope","Classic closure pitfall with var in loops?","All closures share the same var i by reference. By the time callbacks run, i = 5. Fix: use let (block scope per iteration) or IIFE.","// BUG\nfor (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i)); // 3 3 3\n}\n// FIX with let\nfor (let i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i)); // 0 1 2\n}"),
  ("Core","Prototype chain","Advanced","JavaScript inheritance via prototype chain","What is the difference between __proto__ and prototype?","prototype is a property of constructor functions — it's the object that becomes __proto__ of instances. __proto__ is the actual internal [[Prototype]] link on objects. Object.getPrototypeOf() is the standard way to read __proto__.","function Animal(name) { this.name = name; }\nAnimal.prototype.speak = function() { return this.name; };\nconst dog = new Animal('Rex');\nconsole.log(Object.getPrototypeOf(dog) === Animal.prototype); // true"),
  ("Core","this binding","Tricky","Context of 'this' depends on call site","What does 'this' refer to inside an arrow function?","Arrow functions lexically capture 'this' from the enclosing scope — they have no own 'this'. Cannot be used as constructors. Cannot be rebound with .bind().","const obj = {\n  name: 'DevQuiz',\n  regular() { return this.name; },        // 'DevQuiz'\n  arrow: () => this?.name,                // undefined (outer this)\n  delayed() {\n    setTimeout(() => console.log(this.name), 100); // 'DevQuiz' -- arrow captures\n  }\n};"),
  ("Core","Event loop","Advanced","Call stack + Web APIs + callback queue + microtask queue","What executes first: setTimeout(fn,0) or Promise.then?","Promises (.then) are microtasks — they execute before the next macrotask (setTimeout). Microtask queue is drained completely after each macrotask before moving to the next.","console.log('1');\nsetTimeout(() => console.log('2'), 0);\nPromise.resolve().then(() => console.log('3'));\nconsole.log('4');\n// Output: 1, 4, 3, 2"),
  ("Core","== vs ===","Tricky","Loose vs strict equality","What does [] == false evaluate to?","true. [] converts to '' (via toString), then to 0 (number coercion). false converts to 0. 0 == 0 is true. Use === always to avoid type coercion.","console.log([] == false);   // true\nconsole.log('' == false);   // true\nconsole.log(0 == false);    // true\nconsole.log(null == undefined); // true (special case)\nconsole.log(null === undefined); // false"),
  ("Core","typeof & instanceof","Tricky","Type checking operators","What does typeof null return?","'object' — this is a historical bug in JavaScript (bug #62) that cannot be fixed for backwards compatibility. Use === null for null checks.","console.log(typeof null);        // 'object' (bug!)\nconsole.log(typeof undefined);   // 'undefined'\nconsole.log(typeof []);          // 'object'\nconsole.log(Array.isArray([]));  // true\nconsole.log(null === null);      // true (safe check)"),
  ("Async","Promises","Intermediate","Represents future completion or failure","What happens to errors thrown inside Promise executor?","They're caught and the promise is rejected. But errors in setTimeout inside executor are NOT caught — they become uncaught exceptions.","const p = new Promise((resolve, reject) => {\n  throw new Error('sync error'); // caught => rejected\n});\np.catch(e => console.log(e.message)); // 'sync error'\n\n// Promise.all vs allSettled\nPromise.all([p1, p2]);        // rejects if any rejects\nPromise.allSettled([p1, p2]); // always resolves with status"),
  ("Async","async/await","Intermediate","Syntactic sugar over promises","What happens if you don't await an async function?","You get a Promise back, not the resolved value. If the async function throws, the rejection is unhandled (potential crash). Always await or .catch().","async function fetchUser(id) {\n  const res = await fetch(`/users/${id}`);\n  if (!res.ok) throw new Error('Not found');\n  return res.json(); // returns Promise<data>\n}\n// Parallel awaits\nconst [a, b] = await Promise.all([fetchUser(1), fetchUser(2)]);"),
  ("Async","AbortController","Advanced","Cancel fetch requests","Does AbortController work with setTimeout?","Not natively — but you can check signal.aborted manually. It's built for fetch API. Aborting throws AbortError — check err.name === 'AbortError' not err.message.","const controller = new AbortController();\nconst { signal } = controller;\ntry {\n  const res = await fetch(url, { signal });\n} catch (err) {\n  if (err.name === 'AbortError') console.log('Cancelled');\n  else throw err;\n}\ncontroller.abort(); // cancel"),
  ("Arrays","Array methods","Intermediate","map, filter, reduce, find, some, every, flat, flatMap","What is the difference between forEach and map?","forEach returns undefined, always. map returns a new array. Never use map for side effects only — use forEach. forEach cannot be chained, map can.","const nums = [1, 2, 3];\nconst doubled = nums.map(n => n * 2);    // [2,4,6]\nconst evens  = nums.filter(n => n % 2 === 0); // [2]\nconst sum    = nums.reduce((a, n) => a + n, 0); // 6\nnums.flat(Infinity); // flatten nested arrays"),
  ("Objects","Destructuring & spread","Intermediate","Extract values, clone/merge objects/arrays","Does spread do deep copy?","No. Spread is a shallow copy. Nested objects are still references. For deep copy: structuredClone() (modern), JSON.parse(JSON.stringify()) (misses functions/dates), or lodash cloneDeep.","const a = { x: 1, nested: { y: 2 } };\nconst b = { ...a };        // shallow copy\nb.nested.y = 99;           // also changes a.nested.y!\n\n// Deep copy\nconst deep = structuredClone(a);"),
  ("Objects","Object.keys/values/entries","Basic","Enumerable own properties","Does Object.keys include prototype properties?","No. It only returns own enumerable string-keyed properties. Use for...in for prototype chain (then check hasOwnProperty). Symbol-keyed properties are excluded from all three.","const obj = { a: 1, b: 2 };\nObject.keys(obj);    // ['a', 'b']\nObject.values(obj);  // [1, 2]\nObject.entries(obj); // [['a',1], ['b',2]]\n// Convert map to object\nObject.fromEntries(new Map([['a', 1]]))"),
  ("Patterns","Modules (ESM)","Intermediate","import/export vs CommonJS require","What is tree shaking and how do ESM modules enable it?","Tree shaking = dead code elimination. ESM is statically analyzable (imports/exports declared at top level, not runtime). Bundlers (Webpack, Rollup) can determine unused exports at build time. CommonJS require() is dynamic — bundles entire module.","// Named exports -- tree-shakeable\nexport const add = (a, b) => a + b;\nexport const multiply = (a, b) => a * b;\n// Import only what you need\nimport { add } from './math.js'; // multiply excluded by bundler"),
  ("Patterns","Proxy & Reflect","Advanced","Intercept object operations","What is a common real-world use of Proxy?","Reactive data systems (Vue 3 uses Proxy for reactivity). Also: validation, logging, default values, immutable objects.","const handler = {\n  get(target, key) {\n    return key in target ? target[key] : `Key '${key}' missing`;\n  },\n  set(target, key, value) {\n    if (typeof value !== 'number') throw TypeError('Must be number');\n    target[key] = value;\n    return true;\n  }\n};\nconst obj = new Proxy({}, handler);"),
  ("Tricky","NaN","Tricky","Not a Number — but typeof NaN is 'number'","How do you correctly check for NaN?","NaN is the only value not equal to itself (NaN !== NaN). Use Number.isNaN() not global isNaN() — global isNaN coerces the value first (isNaN('hello') = true).","console.log(NaN === NaN);          // false\nconsole.log(isNaN('hello'));       // true (coerces!)\nconsole.log(Number.isNaN('hello')); // false (strict)\nconsole.log(Number.isNaN(NaN));    // true"),
  ("Tricky","Garbage collection","Advanced","Mark-and-sweep algorithm in V8","What is a memory leak in JavaScript?","Unintentional reference retention: global variables, detached DOM nodes held in closures, event listeners not removed, forgotten intervals/timers, WeakMap alternatives not used.","// Memory leak: detached DOM node retained in closure\nlet el = document.getElementById('btn');\nlet leaked = el;\nel.parentNode.removeChild(el); // removed from DOM\nel = null;\n// leaked still holds reference -- node stays in memory\n// Fix: leaked = null; or use WeakRef"),
  ("Tricky","Optional chaining & nullish coalescing","Intermediate","?. and ?? operators","What's the difference between || and ???","|| returns right side for any falsy left (0, '', false, null, undefined). ?? only returns right side for null or undefined. Critical difference: 0 ?? 'default' = 0 (correct); 0 || 'default' = 'default' (wrong if 0 is valid).","const port = config.port ?? 3000;  // 0 is valid\nconst name = user?.profile?.name ?? 'Anonymous';\n// Safe method call\nconst len = str?.trim()?.length ?? 0;"),
  ("Generators","Generator functions","Advanced","Functions that yield multiple values","What are generators useful for in real code?","Infinite sequences, lazy evaluation, custom iterators, async control flow (used internally by async/await). Redux-saga uses generators extensively.","function* range(start, end, step = 1) {\n  for (let i = start; i < end; i += step) yield i;\n}\nconst r = range(0, 10, 2);\nconsole.log([...r]); // [0, 2, 4, 6, 8]\n\n// Infinite Fibonacci\nfunction* fib() {\n  let [a, b] = [0, 1];\n  while (true) { yield a; [a, b] = [b, a + b]; }\n}"),
],

"TypeScript": [
  ("Types","Basic types","Basic","string, number, boolean, null, undefined, symbol, bigint","What is the difference between unknown and any?","any disables all type checking — unsafe. unknown requires type narrowing before use — safe. Use unknown for values you don't know the type of (API responses). Never use any if avoidable.","let a: any = 'hello';\na.toFixed(); // no error -- runtime crash!\n\nlet b: unknown = 'hello';\nif (typeof b === 'string') b.toUpperCase(); // safe\nb.toFixed(); // Error at compile time"),
  ("Types","Union & Intersection","Intermediate","| and & type operators","What is a discriminated union?","Union where each variant has a common literal type field (discriminant). TypeScript narrows type in switch/if blocks using the discriminant. Safer than optional fields.","type Shape =\n  | { kind: 'circle';    radius: number }\n  | { kind: 'rectangle'; width: number; height: number };\n\nfunction area(s: Shape) {\n  switch (s.kind) {\n    case 'circle':    return Math.PI * s.radius ** 2;\n    case 'rectangle': return s.width * s.height;\n  }\n}"),
  ("Types","Generics","Intermediate","Type parameters for reusable type-safe code","What is generic constraint with extends?","extends limits which types can be passed. T extends object means T must have object-like structure. Enables accessing known properties without casting.","function getProperty<T, K extends keyof T>(obj: T, key: K): T[K] {\n  return obj[key];\n}\nconst user = { name: 'Alice', age: 30 };\ngetProperty(user, 'name'); // string\ngetProperty(user, 'xyz');  // Compile error"),
  ("Types","Utility types","Intermediate","Built-in generic types: Partial, Required, Readonly, Pick, Omit, Record, ReturnType","What does NonNullable<T> do?","Removes null and undefined from type T. Useful after null checks to narrow type for TypeScript.","type User = { id: number; name?: string; role: string | null };\ntype Draft     = Partial<User>;       // all optional\ntype Complete   = Required<User>;      // all required\ntype IdAndName  = Pick<User, 'id' | 'name'>;\ntype NoId      = Omit<User, 'id'>;\ntype Config    = Record<string, number>;"),
  ("Types","Template literal types","Advanced","String manipulation at type level","Can you validate URL format at the type level?","Partially. You can enforce string patterns: `${string}://${string}` matches any 'x://y' string. Cannot do full regex validation in types.","type EventName = `on${Capitalize<string>}`;\ntype CSSValue  = `${number}px` | `${number}rem` | `${number}%`;\ntype Direction = 'top' | 'bottom' | 'left' | 'right';\ntype Padding   = `padding-${Direction}`;"),
  ("Types","Conditional types","Advanced","T extends U ? X : Y","What is infer keyword used for?","infer declares a type variable within a conditional type to extract/infer a type from another type. Used to get function return type, promise resolution type, etc.","type ReturnType<T> = T extends (...args: any[]) => infer R ? R : never;\ntype Awaited<T>    = T extends Promise<infer R> ? R : T;\ntype FirstArg<T>   = T extends (first: infer F, ...rest: any[]) => any ? F : never;"),
  ("Types","Mapped types","Advanced","Transform all properties of a type","What's the difference between -? and ?: in mapped types?","?: makes optional; -?: removes optionality (makes required). Similarly, -readonly removes readonly, readonly adds it.","type Mutable<T> = { -readonly [K in keyof T]: T[K] };\ntype Required<T> = { [K in keyof T]-?: T[K] };\n// Transform values too\ntype Nullable<T> = { [K in keyof T]: T[K] | null };\ntype Stringify<T> = { [K in keyof T]: string };"),
  ("Narrowing","Type guards","Intermediate","Narrow union types at runtime","What is the difference between type predicates and assertion functions?","Type predicate: function returns boolean, if true TS narrows the type (is operator). Assertion function: throws if condition fails, TS narrows after call (asserts keyword).","// Type predicate\nfunction isString(x: unknown): x is string {\n  return typeof x === 'string';\n}\n// Assertion function\nfunction assert(condition: unknown, msg: string): asserts condition {\n  if (!condition) throw new Error(msg);\n}"),
  ("Config","tsconfig.json","Intermediate","TypeScript compiler configuration","What does strict flag enable?","strict enables: strictNullChecks, strictFunctionTypes, strictBindCallApply, strictPropertyInitialization, noImplicitAny, noImplicitThis, alwaysStrict, useUnknownInCatchVariables. Always enable.","{\n  \"compilerOptions\": {\n    \"strict\": true,\n    \"target\": \"ES2020\",\n    \"module\": \"ESNext\",\n    \"moduleResolution\": \"bundler\",\n    \"jsx\": \"react-jsx\",\n    \"paths\": { \"@/*\": [\"./src/*\"] }\n  }\n}"),
  ("Tricky","Structural typing","Tricky","TypeScript uses shape, not name for compatibility","Can a class instance satisfy an interface it doesn't explicitly implement?","Yes — TypeScript is structurally typed. If the class has all the properties/methods the interface requires, it's compatible, even without 'implements'.","interface Flyable { fly(): void; }\nclass Bird {\n  fly() { console.log('flap'); }\n  sing() { console.log('tweet'); }\n}\nconst b: Flyable = new Bird(); // Works! Bird has fly()"),
  ("Tricky","Excess property checks","Tricky","TypeScript checks extra properties only on object literals","Why does TypeScript reject {name:'a', extra:1} for type {name:string} but not when assigned via variable?","Object literal directly assigned triggers excess property check. Assigning via variable bypasses it — the variable is checked for structural compatibility only. This is a deliberate design decision.","type User = { name: string };\n// Error: excess property\nconst u: User = { name: 'a', extra: 1 };\n// OK: variable assignment skips excess check\nconst obj = { name: 'a', extra: 1 };\nconst u2: User = obj; // fine"),
  ("Tricky","never type","Tricky","Bottom type — value that never exists","What practical use does never have?","Exhaustiveness checks in switch statements. If a switch handles all cases and you reach default, the value should be never. If a new union member is added without handling, TypeScript errors.","type Shape = 'circle' | 'square';\nfunction process(s: Shape) {\n  switch (s) {\n    case 'circle': break;\n    case 'square': break;\n    default:\n      const _exhaustive: never = s; // Error if new case added\n  }\n}"),
  ("Decorators","Decorators","Advanced","Class/method/property metadata — currently Stage 3","What is the difference between experimental and Stage 3 decorators?","experimentalDecorators (legacy, TS 4.x) uses old TC39 proposal with different semantics. Stage 3 decorators (TS 5.0+) have different API. Breaking change — libraries built for one don't work with the other.","// Stage 3 (TS 5.0+)\nfunction log(target: any, context: ClassMethodDecoratorContext) {\n  return function(...args: any[]) {\n    console.log(`Calling ${String(context.name)}`);\n    return (target as Function).apply(this, args);\n  };\n}\nclass Service {\n  @log greet(name: string) { return `Hi ${name}`; }\n}"),
  ("Performance","const assertions","Intermediate","as const makes values readonly literal types","What does 'as const' do to an array?","Makes all elements readonly literal types instead of widened types. ['a','b'] becomes readonly ['a','b'] — tuple with literal types, not string[]. Useful for config objects.","const ROUTES = ['home', 'about', 'contact'] as const;\ntype Route = typeof ROUTES[number]; // 'home' | 'about' | 'contact'\n\nconst config = { env: 'production', port: 3000 } as const;\n// typeof config = { readonly env: 'production'; readonly port: 3000 }"),
],

"React": [
  ("Core","JSX","Basic","Syntactic sugar over React.createElement","Do you still need to import React in modern React?","No — React 17+ with the new JSX transform automatically imports jsx runtime. But you still need to import React to use React-specific APIs (useState, useEffect, etc.).","// Old (React 16)\nimport React from 'react';\nconst el = <div>Hello</div>;\n// New JSX transform (React 17+)\n// No React import needed for JSX\nconst el = <div>Hello</div>;"),
  ("Hooks","useState","Basic","State in function components","Does setState merge or replace state?","useState setter REPLACES state (unlike class component setState which merges). To update nested object, spread manually: setState(prev => ({...prev, key: val})).","const [user, setUser] = useState({ name: '', age: 0 });\n// WRONG -- loses other fields\nsetUser({ name: 'Alice' });\n// CORRECT\nsetUser(prev => ({ ...prev, name: 'Alice' }));\n// Functional update for derived state\nsetCount(c => c + 1);"),
  ("Hooks","useEffect","Intermediate","Side effects in function components","What is the dependency array contract?","Every value from component scope (props, state, variables) used inside useEffect MUST be in deps array. Omitting them causes stale closures. ESLint react-hooks/exhaustive-deps enforces this.","useEffect(() => {\n  const id = setInterval(() => setCount(c => c + 1), 1000);\n  return () => clearInterval(id); // cleanup\n}, []); // [] = run once on mount\n\n// Runs when userId changes\nuseEffect(() => { fetchUser(userId); }, [userId]);"),
  ("Hooks","useRef","Intermediate","Mutable reference that persists across renders","When should you use useRef vs useState?","useRef for values that don't need to trigger re-render: DOM references, previous values, timers, external library instances. useState for values that affect the UI.","const inputRef = useRef<HTMLInputElement>(null);\nconst prevCount = useRef(count);\n\nuseEffect(() => { prevCount.current = count; });\n\n// Access DOM\nconst focus = () => inputRef.current?.focus();\nreturn <input ref={inputRef} />;"),
  ("Hooks","useMemo & useCallback","Intermediate","Memoize values and callbacks","When does memoization actually help?","Only when: (1) computation is expensive (>1ms), (2) reference equality matters (object/array passed to memoized child). Premature memoization adds overhead. Profile first.","const filtered = useMemo(\n  () => items.filter(i => i.active),\n  [items] // recomputes only when items changes\n);\nconst handleClick = useCallback(\n  () => onSelect(id),\n  [id, onSelect] // stable reference for memo'd children\n);"),
  ("Hooks","Custom hooks","Intermediate","Extract stateful logic into reusable functions","Must custom hooks start with 'use'?","Yes — it's enforced by the react-hooks ESLint plugin. The 'use' prefix tells React the function may contain hooks, enabling proper rules-of-hooks checking. Without it, hooks inside won't be validated.","function useLocalStorage<T>(key: string, initial: T) {\n  const [value, setValue] = useState<T>(() => {\n    try { return JSON.parse(localStorage.getItem(key)!) ?? initial; }\n    catch { return initial; }\n  });\n  const set = useCallback((v: T) => {\n    setValue(v);\n    localStorage.setItem(key, JSON.stringify(v));\n  }, [key]);\n  return [value, set] as const;\n}"),
  ("Hooks","useReducer","Intermediate","Manage complex state with reducer pattern","When to use useReducer over useState?","Complex state with multiple sub-values, state transitions that depend on previous state, when multiple handlers share similar state logic. Also: when you want to pass dispatch (stable) instead of multiple setState callbacks.","type Action = { type: 'inc' } | { type: 'dec' } | { type: 'reset'; payload: number };\nfunction reducer(state: number, action: Action): number {\n  switch (action.type) {\n    case 'inc':   return state + 1;\n    case 'dec':   return state - 1;\n    case 'reset': return action.payload;\n  }\n}"),
  ("Hooks","useContext","Intermediate","Consume React context","Does useContext cause re-renders for ALL consumers when context changes?","Yes — all components that call useContext(MyContext) re-render when context value changes, even if they only use a part that didn't change. Split contexts by update frequency or use state manager.","const ThemeCtx = createContext<'light' | 'dark'>('light');\n\nfunction ThemeProvider({ children }: { children: ReactNode }) {\n  const [theme, setTheme] = useState<'light' | 'dark'>('light');\n  return (\n    <ThemeCtx.Provider value={theme}>\n      {children}\n    </ThemeCtx.Provider>\n  );\n}"),
  ("Performance","React.memo","Intermediate","Skip re-render if props unchanged (shallow comparison)","Does React.memo do deep comparison?","No. Shallow comparison — objects/arrays by reference. Pass a custom compareFn as second arg for deep comparison. But deep comparison itself has cost.","const Card = React.memo(({ user }) => (\n  <div>{user.name}</div>\n), (prev, next) => prev.user.id === next.user.id); // custom compare\n\n// memo is useless if parent passes new object literal each render\n// WRONG: <Card user={{ name: 'Alice' }} /> -- new object every render"),
  ("Performance","Reconciliation","Advanced","React's diffing algorithm (Fiber)","What is the key prop for and why must it be stable?","key tells React which list item corresponds to which DOM node across re-renders. Unstable keys (index) cause React to unmount/mount instead of update, losing state and causing poor performance.","// BAD: index as key -- loses state on reorder\n{items.map((item, i) => <Card key={i} item={item} />)}\n// GOOD: stable unique id\n{items.map(item => <Card key={item.id} item={item} />)}"),
  ("Patterns","Error Boundaries","Advanced","Class component to catch JS errors in tree","Why can't function components be error boundaries?","Error boundaries require componentDidCatch and getDerivedStateFromError lifecycle methods, which only exist on class components. Use react-error-boundary library for function component API.","class ErrorBoundary extends Component {\n  state = { error: null };\n  static getDerivedStateFromError(error) {\n    return { error };\n  }\n  componentDidCatch(error, info) {\n    logError(error, info);\n  }\n  render() {\n    return this.state.error\n      ? <FallbackUI /> : this.props.children;\n  }\n}"),
  ("Patterns","Portals","Advanced","Render outside DOM hierarchy","When do you use portals?","Modals, tooltips, dropdowns — when you need the component logically inside a parent but visually outside (to avoid z-index/overflow issues). Events still bubble through React tree, not DOM tree.","function Modal({ children }) {\n  return ReactDOM.createPortal(\n    <div className='modal-overlay'>{children}</div>,\n    document.getElementById('portal-root')!\n  );\n}"),
  ("Patterns","Compound components","Advanced","Components that share implicit state","What problem do compound components solve?","Rigid prop-drilling interfaces. Instead of <Select options={[...]} onSelect={fn} />, compound components give consumers layout control: <Select><Select.Option /><Select.Trigger /></Select>.","const TabCtx = createContext(null);\nfunction Tabs({ children }) {\n  const [active, setActive] = useState(0);\n  return <TabCtx.Provider value={{ active, setActive }}>{children}</TabCtx.Provider>;\n}\nTabs.Tab = function Tab({ index, children }) {\n  const { active, setActive } = useContext(TabCtx);\n  return <button onClick={() => setActive(index)} aria-selected={active === index}>{children}</button>;\n};"),
  ("Tricky","Batching","Tricky","React groups multiple setState calls into one re-render","Did React 18 change batching behavior?","Yes. React 17: batching only inside React event handlers. React 18: automatic batching everywhere — setTimeout, promises, native event listeners. Use flushSync() to opt out.","// React 18: both setters batched = 1 re-render\nsetTimeout(() => {\n  setCount(c => c + 1);\n  setFlag(f => !f);\n}, 0);\n// Force immediate re-render\nimport { flushSync } from 'react-dom';\nflushSync(() => setCount(c => c + 1));"),
  ("Tricky","Strict Mode","Tricky","Double-invokes effects in development to detect side effects","Why does useEffect run twice in development?","React 18 StrictMode intentionally mounts, unmounts, then remounts components to verify effects have proper cleanup. Shows bugs where cleanup is missing. Only in dev — not production.","// This will run twice in dev -- intentional\nuseEffect(() => {\n  const sub = eventBus.subscribe(handler);\n  return () => sub.unsubscribe(); // cleanup REQUIRED\n}, []);"),
  ("Tricky","Stale closures","Tricky","Event handlers capture old state values","How do you fix stale state in event handlers?","Use the functional update form of setState: setState(prev => prev + 1). Or useRef to track latest value. This is why useReducer with dispatch is often safer.","// BUG: count is stale 0 in closure\nconst [count, setCount] = useState(0);\nuseEffect(() => {\n  window.addEventListener('click', () => {\n    console.log(count); // always 0!\n    setCount(count + 1); // bug: adds 1 to old value\n  });\n}, []);\n// FIX: functional update\nsetCount(c => c + 1);"),
  ("Concurrent","Concurrent features","Advanced","React 18 concurrent rendering: useTransition, useDeferredValue, Suspense","What does useTransition do?","Marks state updates as non-urgent. React can interrupt and deprioritize them when urgent updates (user input) arrive. Returns [isPending, startTransition].","const [isPending, startTransition] = useTransition();\n\nfunction handleSearch(q) {\n  setQuery(q); // urgent: update input immediately\n  startTransition(() => {\n    setResults(filterItems(q)); // non-urgent: can be interrupted\n  });\n}"),
  ("Concurrent","Suspense & lazy","Advanced","Code splitting and async rendering boundaries","Can Suspense catch data fetching errors?","No — Suspense only handles the loading state (when promise is pending). Errors are caught by Error Boundaries. Use both together: ErrorBoundary wrapping Suspense.","const LazyPage = React.lazy(() => import('./Page'));\n\n<ErrorBoundary fallback={<Error />}>\n  <Suspense fallback={<Spinner />}>\n    <LazyPage />\n  </Suspense>\n</ErrorBoundary>"),
],

"React Native": [
  ("Core","Core components","Basic","View, Text, TextInput, ScrollView, FlatList, Image, TouchableOpacity","When to use ScrollView vs FlatList?","ScrollView renders all children at once — bad for long lists. FlatList is virtualized — renders only visible items. Use FlatList for >20 items; ScrollView for small content or horizontal scrollers.","<FlatList\n  data={items}\n  keyExtractor={item => item.id}\n  renderItem={({ item }) => <Card item={item} />}\n  initialNumToRender={10}\n  getItemLayout={(_, index) => ({ length: 80, offset: 80 * index, index })}\n/>"),
  ("Core","StyleSheet","Basic","JS-based styling, similar to CSS but camelCase","Why use StyleSheet.create over plain objects?","StyleSheet.create validates styles in development, sends IDs not objects across the JS-Native bridge (performance), and enables caching. Plain objects create new references each render.","const styles = StyleSheet.create({\n  container: { flex: 1, backgroundColor: '#fff', padding: 16 },\n  text: { fontSize: 16, color: '#333', fontWeight: '600' },\n  // Units are dp (density-independent pixels) -- no 'px'\n});"),
  ("Core","Flexbox in RN","Intermediate","Same as CSS Flexbox but with different defaults","What are the main Flexbox defaults that differ in React Native?","flexDirection defaults to 'column' (not 'row'). flex: 1 fills available space. alignContent defaults to 'flex-start'. No display: grid — Flexbox is the only layout system.","<View style={{ flex: 1, flexDirection: 'row', gap: 8 }}>\n  <View style={{ flex: 1, backgroundColor: 'red' }} />\n  <View style={{ flex: 2, backgroundColor: 'blue' }} />\n</View>"),
  ("Navigation","React Navigation","Intermediate","Stack, Tab, Drawer navigators","What is the difference between navigate and push?","navigate goes to existing screen in stack (no duplicate if already there). push always adds a new screen, allowing duplicate routes. For detail screens, push is usually correct.","// navigation object from useNavigation() or prop\nnavigation.navigate('Profile', { userId: 42 });\nnavigation.push('Profile', { userId: 43 }); // new instance\nnavigation.goBack();\nnavigation.replace('Home'); // replace current screen"),
  ("Navigation","Deep linking","Advanced","URL schemes and universal links","What is the difference between URL schemes and universal links?","URL schemes (myapp://) work in all apps but can be intercepted by any app claiming the scheme. Universal links (https://domain.com/path) are verified via AASA file on your domain — can't be spoofed, also work as web URLs.","// app.json (Expo)\n{\n  'scheme': 'devquiz',\n  'intentFilters': [{\n    'action': 'VIEW',\n    'data': [{ 'scheme': 'https', 'host': 'devquiz.app' }]\n  }]\n}"),
  ("Performance","FlatList optimization","Advanced","Virtualized lists for large datasets","What is getItemLayout and when is it critical?","getItemLayout pre-computes item positions — enables FlatList to skip measurement and scroll directly to any index without rendering intermediaries. Required for scrollToIndex to work reliably.","<FlatList\n  data={data}\n  getItemLayout={(_, index) => ({\n    length: ITEM_HEIGHT,\n    offset: ITEM_HEIGHT * index,\n    index\n  })}\n  removeClippedSubviews={true}\n  maxToRenderPerBatch={10}\n  windowSize={5}\n/>"),
  ("Performance","JS Bridge & JSI","Advanced","Communication between JS and Native threads","What is JSI and why is it faster than the old bridge?","Old bridge: async, serialized JSON messages between JS and Native — latency, no direct access. JSI (JavaScript Interface): synchronous, direct C++ calls from JS to native. Enables Fabric (new renderer) and TurboModules. No serialization overhead.","// Old Bridge (async)\nNativeModules.MyModule.doThing(args, callback);\n// JSI / TurboModules (sync or async)\nimport { NativeMyModule } from './NativeMyModule';\nNativeMyModule.doThing(args); // direct C++ call"),
  ("Performance","Hermes","Intermediate","JavaScript engine optimised for React Native","What advantages does Hermes provide?","Pre-compiled bytecode (faster startup), lower memory footprint, built-in debugging/profiling. Enabled by default in React Native 0.70+. Disadvantage: some JS features lag behind V8 (though mostly caught up).","// android/app/build.gradle\nproject.ext.react = [\n  enableHermes: true // enabled by default 0.70+\n]"),
  ("Animations","Animated API","Intermediate","Declarative animations running on native thread","When to use Animated vs Reanimated?","Animated: simpler, built-in, runs on JS thread (can drop frames). Reanimated 2/3: worklets run on UI thread — 60/120fps guaranteed, handles gestures smoothly. Use Reanimated for any gesture-driven animation.","const opacity = useRef(new Animated.Value(0)).current;\nAnimated.timing(opacity, {\n  toValue: 1,\n  duration: 300,\n  useNativeDriver: true, // ALWAYS use if possible\n}).start();\n<Animated.View style={{ opacity }} />"),
  ("Animations","Reanimated 3","Advanced","UI-thread animations with worklets","What is a worklet in Reanimated?","A JavaScript function marked with 'worklet' directive that runs on the UI thread. Shared values communicate between JS and UI thread. Enables gesture + animation synchronization without JS thread.","import { useSharedValue, useAnimatedStyle, withSpring } from 'react-native-reanimated';\nconst offset = useSharedValue(0);\nconst animStyle = useAnimatedStyle(() => ({\n  transform: [{ translateX: offset.value }]\n}));\noffset.value = withSpring(100); // smooth, UI thread"),
  ("Platform","Platform-specific code","Intermediate","Platform.OS, .select(), and file extensions","What is the difference between Platform.select and file extension splitting?","Platform.select is runtime conditional — bundles both platforms. File extensions (.ios.js / .android.js) are resolved by Metro at build time — smaller bundle, true separation. Use file extensions for significantly different implementations.","// Platform.select\nconst shadow = Platform.select({\n  ios: { shadowColor: '#000', shadowOpacity: 0.2 },\n  android: { elevation: 4 }\n});\n// File extension (Metro resolves at build time)\n// Button.ios.tsx -- iOS only\n// Button.android.tsx -- Android only"),
  ("Tricky","Metro bundler","Intermediate","RN's JavaScript bundler (not Webpack)","How is Metro different from Webpack?","Metro is designed for RN: fast incremental bundling, built-in HMR, no tree shaking (bundles entire module), different module resolution. Doesn't support all webpack plugins/loaders.","// metro.config.js\nmodule.exports = {\n  resolver: {\n    sourceExts: ['ts', 'tsx', 'js', 'jsx'],\n    extraNodeModules: { '@': path.resolve(__dirname, 'src') }\n  },\n  transformer: { babelTransformerPath: require.resolve('react-native-svg-transformer') }\n};"),
  ("Tricky","AsyncStorage pitfalls","Tricky","Async key-value storage, replaces localStorage","What are the limitations of AsyncStorage?","Not encrypted, 6MB limit on Android by default, async (can't read synchronously), no query/filtering. For large structured data use SQLite (expo-sqlite). For sensitive data use expo-secure-store (Keychain/Keystore).","import AsyncStorage from '@react-native-async-storage/async-storage';\n// Always try/catch -- can fail if storage full\ntry {\n  await AsyncStorage.setItem('key', JSON.stringify(value));\n  const raw = await AsyncStorage.getItem('key');\n  const data = raw ? JSON.parse(raw) : null;\n} catch(e) { console.error(e); }"),
  ("Tricky","KeyboardAvoidingView","Tricky","Adjusts layout when keyboard appears","Why does KeyboardAvoidingView behave differently on iOS vs Android?","Android handles keyboard by resizing the window (windowSoftInputMode=adjustResize) — often no KAV needed. iOS overlays keyboard without resize — KAV required. Use behavior='padding' on iOS, behavior='height' or none on Android.","<KeyboardAvoidingView\n  style={{ flex: 1 }}\n  behavior={Platform.OS === 'ios' ? 'padding' : 'height'}\n  keyboardVerticalOffset={Platform.OS === 'ios' ? 88 : 0}\n>"),
  ("New Architecture","Fabric & TurboModules","Advanced","React Native's new architecture (stable in 0.74+)","What is the new architecture and should you migrate?","New architecture: Fabric (new renderer, synchronous layout), TurboModules (JSI-based native modules), Codegen (type-safe native bridge). RN 0.76 enables it by default. Migrate if using RN 0.74+ and your native deps support it.","// Check native module support\n// package.json of third-party libs should have:\n'codegenConfig': {\n  'name': 'MyModuleSpec',\n  'type': 'modules',\n  'jsSrcsDir': 'src'\n}"),
],

"Next.js": [
  ("Rendering","SSR vs SSG vs ISR vs CSR","Basic","Four rendering strategies in Next.js","What is ISR and when should you use it?","ISR (Incremental Static Regeneration): static HTML built at build time, regenerated in background after revalidate seconds. Best for: semi-static content (blog posts, product pages) that changes occasionally. Combines SSG performance with near-real-time data.","// App Router (Next 13+)\nasync function ProductPage({ params }) {\n  const product = await fetch(`/api/products/${params.id}`, {\n    next: { revalidate: 60 } // ISR: 60 second cache\n  }).then(r => r.json());\n  return <div>{product.name}</div>;\n}"),
  ("Rendering","Server Components","Advanced","React Server Components in App Router","Can Server Components use hooks?","No. Hooks (useState, useEffect, etc.) require a client-side runtime. Server Components run on the server only. Add 'use client' directive to make a component a Client Component. Server Components can import Client Components but not vice versa (without passing as children/props).","// Default: Server Component\nasync function UserList() {\n  const users = await db.query('SELECT * FROM users');\n  return <ul>{users.map(u => <li key={u.id}>{u.name}</li>)}</ul>;\n}\n// Client Component\n'use client';\nfunction Counter() {\n  const [n, setN] = useState(0);\n  return <button onClick={() => setN(n+1)}>{n}</button>;\n}"),
  ("Rendering","Streaming & Suspense","Advanced","Stream HTML from server progressively","What is the performance benefit of streaming?","First byte reaches client immediately (good TTFB). Important content renders without waiting for slow data fetches. Slow parts stream in later wrapped in Suspense. Dramatically improves LCP for data-heavy pages.","// Loading.tsx auto-wraps page in Suspense boundary\n// app/dashboard/loading.tsx\nexport default function Loading() { return <Skeleton />; }\n\n// Manual Suspense for fine-grained streaming\n<Suspense fallback={<RecommendationsSkeleton />}>\n  <Recommendations /> {/* streams separately */}\n</Suspense>"),
  ("Routing","App Router","Intermediate","File-based routing with React Server Components","What is the difference between layout.tsx and template.tsx?","layout.tsx: shared UI across routes, state preserved on navigation (doesn't unmount). template.tsx: same but creates new instance on each navigation — useful for enter/exit animations or resetting state.","app/\n  layout.tsx       -- persistent shell\n  page.tsx         -- home route /\n  dashboard/\n    layout.tsx     -- nested layout (sidebar)\n    page.tsx       -- /dashboard\n    settings/\n      page.tsx     -- /dashboard/settings"),
  ("Routing","Route handlers","Intermediate","API routes in App Router (app/api)","What HTTP methods are supported in route handlers?","GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS. Export a function with the matching name. Default GET is cached; POST/PUT/DELETE are not. Add cache: 'no-store' to opt out of GET caching.","// app/api/users/route.ts\nimport { NextRequest, NextResponse } from 'next/server';\nexport async function GET(req: NextRequest) {\n  const users = await db.getUsers();\n  return NextResponse.json(users);\n}\nexport async function POST(req: NextRequest) {\n  const body = await req.json();\n  const user = await db.createUser(body);\n  return NextResponse.json(user, { status: 201 });\n}"),
  ("Routing","Middleware","Advanced","Run code before request completes","What can middleware NOT do?","Cannot use Node.js APIs (no fs, no database drivers) — runs in Edge runtime. Cannot return JSX. Cannot import large node_modules — bundle size limit. Use for auth checks, redirects, geolocation, A/B testing headers.","// middleware.ts (root level)\nimport { NextResponse } from 'next/server';\nimport type { NextRequest } from 'next/server';\nexport function middleware(req: NextRequest) {\n  const token = req.cookies.get('auth-token');\n  if (!token && req.nextUrl.pathname.startsWith('/dashboard')) {\n    return NextResponse.redirect(new URL('/login', req.url));\n  }\n}\nexport const config = { matcher: '/dashboard/:path*' };"),
  ("Data","Server Actions","Advanced","Async functions on server called from client","Are Server Actions secure against CSRF?","Yes — Next.js automatically adds CSRF protection via origin checking and CORS headers for Server Actions. They receive a unique action ID that isn't guessable.","// Define in server component or 'use server' file\n'use server';\nasync function createPost(formData: FormData) {\n  const title = formData.get('title') as string;\n  await db.posts.create({ title, userId: auth.id });\n  revalidatePath('/posts');\n}\n// Use directly in form\n<form action={createPost}>\n  <input name='title' />\n  <button type='submit'>Create</button>\n</form>"),
  ("Data","Caching","Advanced","Four cache layers: Request memoization, Data cache, Full Route Cache, Router Cache","How do you opt out of Next.js data caching?","fetch with cache:'no-store', or dynamic = 'force-dynamic' for entire route, or cookies()/headers() usage (makes route dynamic automatically), or revalidatePath/revalidateTag after mutations.","// Route level\nexport const dynamic = 'force-dynamic'; // no cache\nexport const revalidate = 60; // ISR\n\n// Fetch level\nfetch(url, { cache: 'no-store' }); // always fresh\nfetch(url, { next: { revalidate: 3600 } }); // hourly\nfetch(url, { next: { tags: ['posts'] } }); // tag-based"),
  ("Performance","Image optimization","Intermediate","next/image: lazy loading, sizing, format conversion","What does the priority prop do on next/image?","Adds preload link tag and disables lazy loading. Use for LCP images (largest content above fold). Only 1-2 images per page should have priority. All other images lazy load by default.","import Image from 'next/image';\n<Image\n  src='/hero.jpg'\n  alt='Hero'\n  width={1200}\n  height={600}\n  priority // preload -- use for LCP image\n  sizes='(max-width: 768px) 100vw, 50vw'\n/>"),
  ("Performance","Font optimization","Intermediate","next/font: self-hosted, zero layout shift","How does next/font prevent layout shift?","Generates CSS size-adjust and ascent-override to match fallback font metrics exactly. Preloads font. Self-hosts Google Fonts at build time — no external requests, fonts cached at CDN edge.","import { Inter } from 'next/font/google';\nconst inter = Inter({\n  subsets: ['latin'],\n  display: 'swap',\n  variable: '--font-inter'\n});\nexport default function Layout({ children }) {\n  return <html className={inter.variable}>{children}</html>;\n}"),
  ("Tricky","use client boundary","Tricky","'use client' marks component tree boundary","Does 'use client' make all descendants Client Components?","Yes — all imports within a 'use client' tree become Client Components. But you can inject Server Components as children/props — they remain server-rendered. This is the 'component composition' pattern.","// ClientWrapper.tsx\n'use client';\nfunction ClientWrapper({ children }) {\n  const [open, setOpen] = useState(false);\n  return <div>{open && children}</div>;\n}\n// page.tsx (Server)\n<ClientWrapper>\n  <ServerComponent /> {/* still server-rendered */}\n</ClientWrapper>"),
  ("Tricky","generateStaticParams","Tricky","Static path generation for dynamic routes","What happens to paths not in generateStaticParams at build time?","Depends on dynamicParams setting. dynamicParams=true (default): render on demand and cache. dynamicParams=false: 404 for paths not pre-built.","// app/blog/[slug]/page.tsx\nexport async function generateStaticParams() {\n  const posts = await getPosts();\n  return posts.map(p => ({ slug: p.slug }));\n}\nexport const dynamicParams = false; // 404 unknown slugs"),
  ("Tricky","Environment variables","Intermediate","Server vs client env var exposure","Why does NEXT_PUBLIC_ prefix matter?","Only env vars prefixed with NEXT_PUBLIC_ are included in the client bundle. Other vars remain server-only. Exposing secrets without prefix still risks exposure if you pass them as props to Client Components.","// .env.local\nDATABASE_URL=postgres://... # server only\nNEXT_PUBLIC_API_URL=https://api.example.com # client safe\n\n// Usage\nprocess.env.DATABASE_URL // server only\nprocess.env.NEXT_PUBLIC_API_URL // anywhere"),
  ("Advanced","Parallel & Intercepting Routes","Advanced","Simultaneous routes in same layout","What are intercepting routes used for?","Show content in modal without losing background page (Instagram/Twitter photo modals). Intercept a route within the same layout. Direct URL still shows full page.","app/\n  @modal/\n    (.)photo/[id]/\n      page.tsx   -- intercepted: show as modal\n  photo/[id]/\n    page.tsx     -- direct: show as full page\n  layout.tsx     -- renders both {children} {modal}"),
],
}

# ── Build workbook ─────────────────────────────────────────────────────────
INDEX_DATA = []

for cat_name, rows in DATA.items():
    meta = CATS[cat_name]
    sheet = wb.create_sheet(title=cat_name)

    # Column widths
    widths = [22, 22, 14, 40, 50, 60, 50]
    for i, w in enumerate(widths, 1):
        sheet.column_dimensions[get_column_letter(i)].width = w

    # Header row
    headers = ["Topic", "Subtopic", "Difficulty", "Key Concept", "Tricky Interview Q", "Explanation / Answer", "Code Snippet"]
    for c, h in enumerate(headers, 1):
        cell = sheet.cell(row=1, column=c, value=f"{meta['icon']} {h}" if c == 1 else h)
        cell.font = bold_font(11, white=True)
        cell.fill = hdr(HEADER_BG)
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = border
    sheet.row_dimensions[1].height = 30

    # Data rows
    for r, row in enumerate(rows, 2):
        topic, subtopic, diff, concept, question, answer, code = row
        values = [topic, subtopic, diff, concept, question, answer, code]
        diff_color = DIFF_COLOR_MAP = DIFF_COLORS.get(diff, "FFFFFF")
        for c, val in enumerate(values, 1):
            cell = sheet.cell(row=r, column=c, value=val)
            cell.font = reg_font(9 if c == 7 else 10)
            cell.alignment = Alignment(vertical="top", wrap_text=True)
            cell.border = border
            if c == 3:
                cell.fill = hdr(diff_color)
                cell.font = Font(name="Arial", size=10, bold=True, color="1E293B")
                cell.alignment = Alignment(horizontal="center", vertical="center")
            if c == 7:
                cell.fill = hdr("0D1117")
                cell.font = Font(name="Courier New", size=8, color="E2E8F0")
        # Alternating row tint
        if r % 2 == 0:
            for c in range(1, 7):
                if c != 3 and c != 7:
                    sheet.cell(row=r, column=c).fill = hdr("F8FAFC")
        sheet.row_dimensions[r].height = 72

    INDEX_DATA.append((cat_name, meta["icon"], meta["color"], len(rows)))

# ── Index / Cover sheet ────────────────────────────────────────────────────
cover = wb.create_sheet(title="📋 Index", index=0)
cover.column_dimensions["A"].width = 8
cover.column_dimensions["B"].width = 20
cover.column_dimensions["C"].width = 12
cover.column_dimensions["D"].width = 10
cover.column_dimensions["E"].width = 40

# Title
cover.merge_cells("A1:E1")
c = cover["A1"]
c.value = "🚀 DevQuiz — Ultimate Interview Study Guide"
c.font = Font(name="Arial", bold=True, size=18, color="FFFFFF")
c.fill = hdr(HEADER_BG)
c.alignment = Alignment(horizontal="center", vertical="center")
cover.row_dimensions[1].height = 44

cover.merge_cells("A2:E2")
c = cover["A2"]
c.value = "Covering: HTML • CSS • JavaScript • TypeScript • React • React Native • Next.js"
c.font = Font(name="Arial", size=12, color="6366F1")
c.alignment = Alignment(horizontal="center", vertical="center")
cover.row_dimensions[2].height = 28

cover["A4"] = "#"; cover["B4"] = "Technology"; cover["C4"] = "Topics"; cover["D4"] = "Icon"
cover["E4"] = "Difficulty Mix"
for col in ["A","B","C","D","E"]:
    cell = cover[f"{col}4"]
    cell.font = bold_font(11, white=True)
    cell.fill = hdr(HEADER_BG)
    cell.alignment = Alignment(horizontal="center", vertical="center")
    cell.border = border
cover.row_dimensions[4].height = 26

for i, (cat, icon, color, count) in enumerate(INDEX_DATA, 1):
    row = i + 4
    cover.cell(row=row, column=1, value=i).alignment = Alignment(horizontal="center", vertical="center")
    link_cell = cover.cell(row=row, column=2, value=cat)
    link_cell.font = Font(name="Arial", size=11, bold=True, color=color if color != "000000" else "333333")
    link_cell.hyperlink = f"#{cat}!A1"
    cover.cell(row=row, column=3, value=count).alignment = Alignment(horizontal="center", vertical="center")
    cover.cell(row=row, column=4, value=icon).alignment = Alignment(horizontal="center", vertical="center")
    # Difficulty mix description
    cover.cell(row=row, column=5, value="Basic · Intermediate · Advanced · Tricky interview scenarios")
    for col in range(1, 6):
        cell = cover.cell(row=row, column=col)
        cell.border = border
        if i % 2 == 0:
            cell.fill = hdr("F1F5F9")
    cover.row_dimensions[row].height = 22

# Legend
legend_row = len(INDEX_DATA) + 7
cover.merge_cells(f"A{legend_row}:E{legend_row}")
cover[f"A{legend_row}"] = "DIFFICULTY LEGEND"
cover[f"A{legend_row}"].font = bold_font(10, white=True)
cover[f"A{legend_row}"].fill = hdr(HEADER_BG)
cover[f"A{legend_row}"].alignment = Alignment(horizontal="center")

for i, (diff, color) in enumerate(DIFF_COLORS.items()):
    r = legend_row + 1 + i
    c1 = cover.cell(row=r, column=1, value=diff)
    c1.fill = hdr(color)
    c1.font = bold_font(10)
    c1.alignment = Alignment(horizontal="center", vertical="center")
    descriptions = {
        "Basic": "Fundamental knowledge — expected from all candidates",
        "Intermediate": "Solid understanding — mid-level developer questions",
        "Advanced": "Deep expertise — senior / lead developer questions",
        "Tricky": "Gotcha questions, edge cases, common misconceptions"
    }
    c2 = cover.cell(row=r, column=2, value=descriptions[diff])
    c2.font = reg_font(10)
    cover.row_dimensions[r].height = 20

output_path = "/Users/apple/Desktop/DevQuiz_Interview_Study_Guide.xlsx"
wb.save(output_path)
print(f"Saved: {output_path}")
print(f"Total topics: {sum(v for _,_,_,v in INDEX_DATA)}")
