# ─────────────────────────────────────────────────────────────────────────────
# EXTRA topics to add to each sheet
# ─────────────────────────────────────────────────────────────────────────────

RN_EXTRA = [
  # ── Threads ────────────────────────────────────────────────────────────────
  ("Threads","JS Thread","Advanced","Single JavaScript thread — runs React render, business logic, animations","What blocks the JS thread and causes jank?","Heavy synchronous computations, large JSON.parse, synchronous native module calls, unoptimised re-renders. Offload with InteractionManager, requestAnimationFrame, or a background worker (JSI Worklet / react-native-workers).","// Defer work until animations settle\nimport { InteractionManager } from 'react-native';\nuseEffect(() => {\n  const task = InteractionManager.runAfterInteractions(() => {\n    heavyDataProcessing(); // runs after animation completes\n  });\n  return () => task.cancel();\n}, []);"),
  ("Threads","UI Thread (Main Thread)","Advanced","Native UI rendering thread — handles layout, drawing, touch events","Why must you never call setState from the UI thread directly?","UI thread is native (ObjC/Java). JS state lives on the JS thread. Communication happens via the bridge (old arch) or JSI shared values (new arch). Reanimated worklets run ON the UI thread — that's why they're jank-free.","// Reanimated: runs directly on UI thread\nfunction worklet() {\n  'worklet';\n  return Math.sqrt(sharedValue.value * 2); // no bridge roundtrip\n}\n// useAnimatedStyle callbacks are worklets automatically"),
  ("Threads","Native/Shadow Thread","Advanced","Background thread for layout calculation (Yoga engine)","What is the Shadow Thread (Yoga)?","Separate C++ thread running Yoga (Flexbox) layout engine. Computes layout before committing to UI thread. In Fabric (new arch), layout can happen synchronously on the UI thread — eliminates a thread hop.","// No code needed -- happens automatically\n// Old Arch: JS → Bridge → Shadow Thread (Yoga) → UI Thread\n// New Arch: JS → JSI → Fabric (sync layout on UI thread)"),
  ("Threads","InteractionManager","Intermediate","Schedule work after animations complete","What is the difference between InteractionManager and setTimeout(fn, 0)?","setTimeout(0) may interrupt an ongoing animation — runs at next event loop tick regardless. InteractionManager waits until ALL registered interactions (animations, transitions) have completed.","InteractionManager.runAfterInteractions(() => {\n  // Safe to run expensive work -- all animations done\n  setData(processLargeDataset(raw));\n});\n// Register custom interaction\nconst handle = InteractionManager.createInteractionHandle();\nInteractionManager.clearInteractionHandle(handle);"),

  # ── Push Notifications ─────────────────────────────────────────────────────
  ("Push Notifications","FCM Setup (Android)","Intermediate","Firebase Cloud Messaging for Android push","What files are needed for FCM on Android?","google-services.json in android/app/, @react-native-firebase/app + /messaging packages, classpath 'com.google.gms:google-services' in android/build.gradle, apply plugin in android/app/build.gradle.","// Install\nnpx expo install @react-native-firebase/app @react-native-firebase/messaging\n// Request permission\nasync function requestPermission() {\n  const authStatus = await messaging().requestPermission();\n  return authStatus === messaging.AuthorizationStatus.AUTHORIZED\n      || authStatus === messaging.AuthorizationStatus.PROVISIONAL;\n}\n// Get token\nconst token = await messaging().getToken();"),
  ("Push Notifications","APNs Setup (iOS)","Advanced","Apple Push Notification service for iOS","What iOS capabilities must be enabled for push?","Push Notifications entitlement + Background Modes → Remote notifications in Xcode. Also need APNs key (.p8) or certificate in Firebase/backend.","// AppDelegate.m -- register for remote notifications\n[application registerForRemoteNotifications];\n// React Native Firebase handles this automatically\n// Foreground handler\nmessaging().onMessage(async remoteMessage => {\n  // Show local notification while app is in foreground\n  PushNotification.localNotification({\n    title: remoteMessage.notification.title,\n    message: remoteMessage.notification.body,\n  });\n});"),
  ("Push Notifications","Background & Quit state","Advanced","Handling notifications when app is backgrounded or killed","What is the difference between onMessage, onNotificationOpenedApp, and getInitialNotification?","onMessage: foreground only. onNotificationOpenedApp: app in background, user taps notification (app comes to foreground). getInitialNotification: app was QUIT, user taps — call in useEffect on mount to handle cold start.","useEffect(() => {\n  // App opened from QUIT state by notification\n  messaging().getInitialNotification().then(msg => {\n    if (msg) navigate(msg.data.screen);\n  });\n  // App in BACKGROUND, user taps\n  const unsub = messaging().onNotificationOpenedApp(msg => {\n    navigate(msg.data.screen);\n  });\n  return unsub;\n}, []);"),
  ("Push Notifications","Local Notifications","Intermediate","Show notifications triggered by app logic (not server)","When do you need local notifications?","Reminders, alarms, download complete, offline events — anything the app triggers itself without a server. Use expo-notifications or notifee library.","import notifee, { AndroidImportance } from '@notifee/react-native';\nasync function showNotification(title: string, body: string) {\n  const channelId = await notifee.createChannel({\n    id: 'default', name: 'Default', importance: AndroidImportance.HIGH,\n  });\n  await notifee.displayNotification({\n    title, body, android: { channelId, pressAction: { id: 'default' } },\n  });\n}"),
  ("Push Notifications","Notification channels (Android)","Intermediate","Android 8+ requires notification channels","What happens if you don't create a notification channel?","On Android 8+, notifications without a valid channel are silently dropped. Each channel has its own sound, vibration, importance, and can be customised by the user in Settings.","// Create channel once on app start\nawait notifee.createChannel({\n  id: 'orders',\n  name: 'Order Updates',\n  importance: AndroidImportance.HIGH,\n  sound: 'default',\n  vibration: true,\n});\n// User can override channel settings in Android Settings"),
  ("Push Notifications","Expo Notifications","Intermediate","Managed workflow push notifications","Expo push token vs FCM/APNs token?","Expo push token (ExponentPushToken[...]) routes through Expo's push service which forwards to FCM/APNs. Useful for managed workflow. For bare workflow, use FCM/APNs tokens directly for full control.","import * as Notifications from 'expo-notifications';\nasync function registerForPush() {\n  const { status } = await Notifications.requestPermissionsAsync();\n  if (status !== 'granted') return null;\n  const token = (await Notifications.getExpoPushTokenAsync({\n    projectId: Constants.expoConfig.extra.eas.projectId,\n  })).data;\n  return token; // send to your backend\n}"),

  # ── Gesture Handler ─────────────────────────────────────────────────────────
  ("Gestures","react-native-gesture-handler","Intermediate","Native-thread gesture recognition replacing JS touch system","Why use Gesture Handler instead of built-in Touchable?","Built-in touches go JS thread → recognizer → UI thread (laggy). Gesture Handler runs entirely on UI thread — responds at 60/120fps even when JS thread is busy.","import { GestureDetector, Gesture } from 'react-native-gesture-handler';\nconst tap = Gesture.Tap()\n  .numberOfTaps(2)\n  .onEnd(() => { runOnJS(handleDoubleTap)(); });\nconst pinch = Gesture.Pinch()\n  .onUpdate(e => { scale.value = savedScale.value * e.scale; });\nconst composed = Gesture.Simultaneous(tap, pinch);\n<GestureDetector gesture={composed}><Animated.View style={animStyle} /></GestureDetector>"),
  ("Gestures","Swipe to dismiss","Advanced","Pan gesture + Reanimated for sheet/card dismissal","How do you prevent child ScrollView from consuming the swipe gesture?","Use activeOffsetX or activeOffsetY on the pan gesture to define threshold before activation, so vertical scroll still works until horizontal swipe is clearly intended.","const pan = Gesture.Pan()\n  .activeOffsetX([-10, 10]) // activate only on horizontal\n  .onUpdate(e => { translateX.value = e.translationX; })\n  .onEnd(e => {\n    if (Math.abs(e.translationX) > 100) {\n      translateX.value = withTiming(500, {}, () => runOnJS(onDismiss)());\n    } else {\n      translateX.value = withSpring(0);\n    }\n  });"),

  # ── Testing ─────────────────────────────────────────────────────────────────
  ("Testing","Jest + React Native Testing Library","Intermediate","Unit/integration testing for RN components","What is the difference between getBy and queryBy?","getBy: throws if not found. queryBy: returns null if not found (use for asserting absence). findBy: async version with retry — waits for element to appear.","import { render, fireEvent, waitFor } from '@testing-library/react-native';\ntest('shows user name after load', async () => {\n  const { getByText, queryByTestId } = render(<UserCard userId='1' />);\n  expect(queryByTestId('skeleton')).toBeTruthy();\n  await waitFor(() => getByText('Alice'));\n  expect(queryByTestId('skeleton')).toBeNull();\n  fireEvent.press(getByText('Follow'));\n});"),
  ("Testing","Mocking native modules","Advanced","Mock modules that rely on native code","Why do native modules fail in Jest?","Jest runs in Node — no native runtime. Mock the module to return predictable values. Use jest.mock() at top of test file or in __mocks__ folder.","// __mocks__/@react-native-async-storage/async-storage.js\nconst store = {};\nexport default {\n  setItem: jest.fn((k, v) => Promise.resolve((store[k] = v))),\n  getItem: jest.fn(k => Promise.resolve(store[k] ?? null)),\n  removeItem: jest.fn(k => Promise.resolve(delete store[k])),\n  clear: jest.fn(() => Promise.resolve(Object.keys(store).forEach(k => delete store[k]))),\n};"),
  ("Testing","Detox E2E testing","Advanced","End-to-end testing on real device/simulator","What is Detox's grey box testing approach?","Grey box: Detox synchronizes with app's internal state (knows when animations, network, async ops are idle) before running assertions. Unlike Appium (black box), no arbitrary sleeps needed.","// detox.config.js\nmodule.exports = { testRunner: 'jest', apps: { 'ios.debug': {\n  type: 'ios.app', binaryPath: 'ios/build/app.app',\n  build: 'xcodebuild ...',\n}}};\n// test.e2e.js\ndescribe('Login', () => {\n  it('should log in successfully', async () => {\n    await element(by.id('email')).typeText('user@test.com');\n    await element(by.id('password')).typeText('password');\n    await element(by.id('login-btn')).tap();\n    await expect(element(by.id('dashboard'))).toBeVisible();\n  });\n});"),

  # ── Native Modules ──────────────────────────────────────────────────────────
  ("Native Modules","Writing a Native Module","Advanced","Bridge JS to platform native code (ObjC/Swift/Java/Kotlin)","When do you need a custom native module?","When no JS library exists: hardware sensors, DRM, Bluetooth, biometrics, custom camera pipelines, calling existing native SDK.","// iOS: RCTCalendarModule.m\n@implementation RCTCalendarModule\nRCT_EXPORT_MODULE();\nRCT_EXPORT_METHOD(createEvent:(NSString *)title\n  resolver:(RCTPromiseResolveBlock)resolve\n  rejecter:(RCTPromiseRejectBlock)reject) {\n  NSNumber *eventId = [self createEventWithTitle:title];\n  if (eventId) resolve(eventId);\n  else reject(@\"E_CREATE\", @\"Failed\", nil);\n}\n@end\n// JS\nimport { NativeModules } from 'react-native';\nawait NativeModules.CalendarModule.createEvent('Meeting');"),
  ("Native Modules","TurboModules (New Arch)","Advanced","JSI-based native modules — type-safe, synchronous","How does TurboModules differ from legacy Native Modules?","Legacy: async bridge, JSON serialization, no type safety at boundary. TurboModules: JSI direct C++ call, Codegen generates type-safe spec from TypeScript, can be synchronous.","// NativeCalendarModule.ts (Codegen spec)\nimport type { TurboModule } from 'react-native';\nimport { TurboModuleRegistry } from 'react-native';\nexport interface Spec extends TurboModule {\n  createEvent(title: string): Promise<number>;\n}\nexport default TurboModuleRegistry.getEnforcing<Spec>('CalendarModule');"),

  # ── State Management ─────────────────────────────────────────────────────────
  ("State Management","Redux Toolkit","Intermediate","Opinionated Redux: createSlice, createAsyncThunk, RTK Query","What does createSlice generate?","Action creators and reducer combined. Immer is built-in — you can write mutating code (obj.count++) and it produces immutable state.","import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';\nconst fetchUser = createAsyncThunk('user/fetch', async (id: string) =>\n  (await fetch(`/api/users/${id}`)).json()\n);\nconst userSlice = createSlice({\n  name: 'user',\n  initialState: { data: null, status: 'idle' },\n  reducers: { logout: state => { state.data = null; } },\n  extraReducers: b => {\n    b.addCase(fetchUser.pending,   s => { s.status = 'loading'; })\n     .addCase(fetchUser.fulfilled, (s, a) => { s.data = a.payload; s.status = 'done'; });\n  },\n});"),
  ("State Management","Zustand","Intermediate","Minimal state management — no boilerplate","Zustand vs Redux — when to choose Zustand?","Zustand for simpler apps/teams — no actions, reducers, dispatching. Redux Toolkit for large teams — explicit patterns, DevTools, RTK Query for caching.","import { create } from 'zustand';\nimport { persist } from 'zustand/middleware';\ninterface AuthStore {\n  user: User | null;\n  login: (user: User) => void;\n  logout: () => void;\n}\nconst useAuth = create<AuthStore>()(persist(\n  set => ({\n    user: null,\n    login: (user) => set({ user }),\n    logout: () => set({ user: null }),\n  }),\n  { name: 'auth-storage', storage: AsyncStorage }\n));"),
  ("State Management","Context vs State Manager","Tricky","When to use React Context vs external state library","What is the main perf problem with Context?","All consumers re-render on any context value change. For frequently-updated state (counters, form values), use Zustand/Redux — they support selectors (only re-render when selected slice changes).","// Context: fine for theme, locale, auth (infrequent updates)\n// Zustand: use selector to prevent unnecessary re-renders\nconst userName = useAuthStore(state => state.user?.name);\n// Only re-renders when user.name changes -- not on unrelated store updates"),

  # ── CodePush & OTA ──────────────────────────────────────────────────────────
  ("Deployment","CodePush / EAS Update","Advanced","Over-the-air JS bundle updates without app store","What can CodePush update and what can't it?","Can update: JS/TS code, images, assets bundled with app. Cannot update: native code (Swift/Kotlin/Java), new native modules, Gradle/Podfile changes — these require a new app store release.","// @microsoft/react-native-code-push\nimport CodePush from 'react-native-code-push';\nconst App = () => <RootNavigator />;\nexport default CodePush({\n  checkFrequency: CodePush.CheckFrequency.ON_APP_RESUME,\n  installMode: CodePush.InstallMode.ON_NEXT_RESUME,\n})(App);\n// EAS Update (Expo)\nnpx eas update --branch production --message 'Fix login crash'"),
  ("Deployment","App signing & release","Advanced","Android keystore, iOS provisioning profiles & certificates","What is the most common release mistake for Android?","Losing the keystore file. Google Play requires the SAME keystore for all updates — if lost, you must publish as a new app. Back it up in multiple secure locations.","# Android: generate keystore\nkeytool -genkey -v -keystore my-release-key.jks\n  -alias my-key-alias -keyalg RSA -keysize 2048\n# gradle.properties (keep out of git)\nKEYSTORE_FILE=my-release-key.jks\nKEY_ALIAS=my-key-alias\nKEY_PASSWORD=...\n# iOS: managed by Xcode / EAS credentials"),
  ("Deployment","EAS Build","Intermediate","Expo Application Services cloud builds","EAS Build vs local build?","EAS Build: reproducible environment, no Xcode/Android Studio needed on dev machine, easy CI. Local: faster iteration, easier debugging native issues, required for custom build configs EAS doesn't support.","# eas.json\n{\n  \"build\": {\n    \"development\": { \"developmentClient\": true, \"distribution\": \"internal\" },\n    \"production\": { \"android\": { \"buildType\": \"apk\" }, \"ios\": { \"simulator\": false } }\n  }\n}\n# Build\neas build --platform android --profile production"),

  # ── Performance ──────────────────────────────────────────────────────────────
  ("Performance","Flipper debugging","Intermediate","Meta's debugging tool for React Native apps","What can you inspect with Flipper?","Network requests, React DevTools, Redux state, database (SQLite, AsyncStorage), layout inspector, crash logs, custom plugins. Essential for RN debugging.","// Enable in debug builds (default in RN 0.62+)\n// Packages: flipper-plugin-network, flipper-plugin-react-query\n// Custom plugin:\nconst flipperClient = require('react-native-flipper');\nflipperClient.addPlugin({\n  getId: () => 'MyPlugin',\n  onConnect: conn => conn.send('data', { key: 'value' }),\n  onDisconnect: () => {},\n});"),
  ("Performance","JS bundle optimization","Advanced","Reduce bundle size for faster startup","How do you measure and reduce RN bundle size?","Use --bundle-output and source-map-explorer to visualize. Lazy require() large libraries. Avoid barrel imports (import * from). Use dynamic imports with React.lazy (Fabric only).","# Analyze bundle\nnpx react-native bundle --platform android --dev false\n  --entry-file index.js --bundle-output output.js\nnpx source-map-explorer output.js output.js.map\n\n// Lazy require inside function\nfunction openPDF(path) {\n  const PDFLib = require('@react-native-pdf/pdflib'); // loaded on demand\n  PDFLib.open(path);\n}"),
  ("Performance","Memory profiling","Advanced","Detect memory leaks in React Native apps","Common memory leak causes in RN?","Event listeners not removed, subscriptions not unsubscribed, timers not cleared, closures holding large data, JS references to unmounted components.","// Always clean up in useEffect\nuseEffect(() => {\n  const subscription = DeviceEventEmitter.addListener('event', handler);\n  const interval = setInterval(poll, 5000);\n  const ws = new WebSocket(url);\n  return () => {\n    subscription.remove();\n    clearInterval(interval);\n    ws.close();\n  };\n}, []);"),

  # ── Offline & Network ────────────────────────────────────────────────────────
  ("Offline","NetInfo","Basic","Detect network connectivity state","Does NetInfo guarantee the user can reach YOUR server?","No — NetInfo detects local connectivity (WiFi/cellular connected), not actual internet access. A user connected to a captive portal shows as connected but can't reach your API.","import NetInfo from '@react-native-community/netinfo';\n// One-time check\nconst state = await NetInfo.fetch();\nconsole.log(state.isConnected, state.type); // 'wifi'|'cellular'|'none'\n// Subscribe to changes\nconst unsub = NetInfo.addEventListener(state => {\n  dispatch(setOnline(state.isConnected));\n});\nreturn () => unsub();"),
  ("Offline","Offline-first strategy","Advanced","Queue mutations and sync when online","What is optimistic UI in a mobile context?","Update UI immediately before server confirms — better UX on slow connections. Roll back on failure. React Query / Redux Toolkit Query support optimistic updates.","// Optimistic update with React Query\nconst mutation = useMutation({\n  mutationFn: (newPost) => api.createPost(newPost),\n  onMutate: async (newPost) => {\n    await queryClient.cancelQueries(['posts']);\n    const previous = queryClient.getQueryData(['posts']);\n    queryClient.setQueryData(['posts'], old => [newPost, ...old]);\n    return { previous }; // rollback context\n  },\n  onError: (err, _, context) => {\n    queryClient.setQueryData(['posts'], context.previous); // rollback\n  },\n});"),

  # ── Accessibility ────────────────────────────────────────────────────────────
  ("Accessibility","RN Accessibility","Intermediate","accessible, accessibilityLabel, accessibilityRole, accessibilityHint","What is accessibilityRole?","Tells screen reader (VoiceOver/TalkBack) what kind of element this is — button, link, header, image, etc. Changes how the reader announces and interacts with it.","<TouchableOpacity\n  accessible\n  accessibilityRole='button'\n  accessibilityLabel='Send message'\n  accessibilityHint='Double tap to send your message'\n  onPress={send}\n>\n  <Image source={sendIcon} />\n</TouchableOpacity>\n// Check VoiceOver: Settings > Accessibility > VoiceOver\n// Check TalkBack: Settings > Accessibility > TalkBack"),

  # ── Expo ─────────────────────────────────────────────────────────────────────
  ("Expo","Expo vs Bare workflow","Basic","Managed vs ejected React Native","When should you eject from Expo managed workflow?","When you need: custom native modules not available in Expo SDK, specific native config, advanced build customisation, or the Expo SDK doesn't support a required native feature yet.","# Check if expo module exists before ejecting\nnpx expo install expo-camera expo-location expo-notifications\n# If not available:\nnpx expo prebuild  # generates native ios/ android/ folders\n# Then use bare workflow -- still uses Expo packages"),
  ("Expo","Expo Router","Intermediate","File-based routing for React Native (like Next.js)","How does Expo Router handle deep links?","Automatic — file structure defines URL scheme. /app/profile/[id].tsx maps to myapp://profile/123 automatically with expo-router's Link handling.","// app/(tabs)/index.tsx  -> /\n// app/(tabs)/profile/[id].tsx -> /profile/123\nimport { Link, useLocalSearchParams } from 'expo-router';\nconst { id } = useLocalSearchParams();\n<Link href={{ pathname: '/profile/[id]', params: { id: user.id } }}>\n  View Profile\n</Link>"),
]

# ─── JavaScript extra ─────────────────────────────────────────────────────────
JS_EXTRA = [
  ("Design Patterns","Module pattern","Intermediate","Encapsulate code and expose public API","What is the revealing module pattern?","Define everything privately, return an object exposing only public parts. Predecessor to ES modules.","const Counter = (() => {\n  let count = 0; // private\n  const increment = () => ++count;\n  const reset = () => { count = 0; };\n  return { increment, reset, getCount: () => count }; // public\n})();\nCounter.increment(); Counter.increment();\nCounter.getCount(); // 2"),
  ("Design Patterns","Observer pattern","Advanced","Pub/Sub — decouple emitters from listeners","How does EventEmitter implement Observer?","Maintains a map of event→listeners. emit iterates and calls each. on/off add/remove. Node.js, React Native DeviceEventEmitter, and browser EventTarget all use this pattern.","class EventEmitter {\n  #events = new Map();\n  on(event, fn) {\n    (this.#events.get(event) ?? this.#events.set(event, []).get(event)).push(fn);\n    return () => this.off(event, fn);\n  }\n  off(event, fn) { this.#events.set(event, (this.#events.get(event) ?? []).filter(f => f !== fn)); }\n  emit(event, ...args) { (this.#events.get(event) ?? []).forEach(fn => fn(...args)); }\n}"),
  ("Design Patterns","Factory pattern","Intermediate","Create objects without specifying exact class","When to use Factory over constructor?","When creation logic is complex, when subclass to create depends on input, or when you want to hide implementation details.","function createUser(role) {\n  const base = { id: crypto.randomUUID(), role };\n  switch (role) {\n    case 'admin': return { ...base, permissions: ['read','write','delete'], level: 'high' };\n    case 'editor': return { ...base, permissions: ['read','write'], level: 'mid' };\n    default: return { ...base, permissions: ['read'], level: 'low' };\n  }\n}"),
  ("Design Patterns","Singleton pattern","Intermediate","One instance per application","Is Singleton an antipattern?","Often yes — creates hidden global state, makes testing hard (shared state between tests). Acceptable for: logger, DB connection pool, config object. Use dependency injection instead where possible.","class Database {\n  static #instance = null;\n  #connection;\n  static getInstance() {\n    Database.#instance ??= new Database();\n    return Database.#instance;\n  }\n  connect(url) { this.#connection = createConnection(url); }\n}\n// Always same instance\nDatabase.getInstance() === Database.getInstance(); // true"),
  ("Design Patterns","Strategy pattern","Advanced","Select algorithm at runtime","Real-world JS example of Strategy?","Sorting strategies, payment processors, authentication methods, validation rules.","const validators = {\n  email: v => /^[^@]+@[^@]+$/.test(v),\n  phone: v => /^\\d{10}$/.test(v),\n  username: v => v.length >= 3 && /^[a-z0-9_]+$/i.test(v),\n};\nfunction validate(value, strategy) {\n  const fn = validators[strategy];\n  if (!fn) throw new Error(`Unknown strategy: ${strategy}`);\n  return fn(value);\n}\nvalidate('test@mail.com', 'email'); // true"),
  ("Functional","Pure functions & immutability","Intermediate","No side effects, same input → same output","Why prefer immutability in JS?","Predictability, easier debugging, enables time-travel debugging, React/Redux state comparison (===) works correctly, prevents shared mutable state bugs.","// Mutable -- bad\nconst addItem = (arr, item) => { arr.push(item); return arr; };\n// Immutable -- good\nconst addItem = (arr, item) => [...arr, item];\nconst updateUser = (user, changes) => ({ ...user, ...changes });\nconst removeById = (arr, id) => arr.filter(x => x.id !== id);"),
  ("Functional","Composition & pipe","Advanced","Combine functions: output of one feeds next","What is the difference between compose and pipe?","compose: right-to-left (mathematical). pipe: left-to-right (more readable for data transformation pipelines).","const pipe = (...fns) => x => fns.reduce((v, f) => f(v), x);\nconst compose = (...fns) => x => fns.reduceRight((v, f) => f(v), x);\n\nconst processUser = pipe(\n  user => ({ ...user, name: user.name.trim() }),\n  user => ({ ...user, email: user.email.toLowerCase() }),\n  user => ({ ...user, slug: user.name.replace(/\\s+/g, '-') }),\n);\nprocessUser({ name: ' Alice ', email: 'ALICE@MAIL.COM' });"),
  ("Browser APIs","Web Workers","Advanced","Run JS in background thread — no DOM access","What data can you NOT pass to a Web Worker?","Functions, DOM nodes, class instances with methods. Transferable objects (ArrayBuffer, OffscreenCanvas) are transferred (moved, not copied) — the original is neutered.","// worker.js\nself.onmessage = ({ data }) => {\n  const result = expensiveCalculation(data);\n  self.postMessage(result);\n};\n// main.js\nconst worker = new Worker('worker.js');\nworker.postMessage(largeArray);\nworker.onmessage = ({ data }) => setResults(data);\nworker.terminate(); // clean up"),
  ("Browser APIs","WebSockets","Intermediate","Full-duplex real-time communication","What is the difference between WebSocket and Server-Sent Events?","WebSocket: bidirectional, binary + text, must manage reconnection. SSE: unidirectional (server→client only), text only, auto-reconnects, simpler. Use SSE for live feeds; WebSocket for chat/games.","const ws = new WebSocket('wss://api.devquiz.app/ws');\nws.onopen    = () => ws.send(JSON.stringify({ type: 'subscribe', channel: 'quiz' }));\nws.onmessage = ({ data }) => dispatch(handleMessage(JSON.parse(data)));\nws.onerror   = (err) => console.error('WS error', err);\nws.onclose   = () => setTimeout(reconnect, 1000); // auto-reconnect"),
  ("Browser APIs","Service Workers","Advanced","Proxy between browser and network — enables PWA","What is the lifecycle of a Service Worker?","Install → Activate → Fetch intercept. New SW waits in 'waiting' state while old SW controls open pages. skipWaiting() + clients.claim() force immediate takeover.","// sw.js\nconst CACHE = 'v1';\nself.addEventListener('install', e => {\n  e.waitUntil(caches.open(CACHE).then(c => c.addAll(['/','index.html','app.js'])));\n});\nself.addEventListener('fetch', e => {\n  e.respondWith(\n    caches.match(e.request).then(cached => cached ?? fetch(e.request))\n  );\n});"),
  ("Performance","JS Performance","Advanced","Profiling, memory, rendering optimization","What causes memory leaks in browser JS?","Detached DOM nodes held in closures, forgotten event listeners, setInterval not cleared, cache with no eviction, WeakRef alternatives not used.","// Profile with Performance API\nperformance.mark('start');\nheavyOperation();\nperformance.mark('end');\nperformance.measure('heavy', 'start', 'end');\nconsole.log(performance.getEntriesByName('heavy')[0].duration);\n// Avoid: memory leak from detached node\nlet el = document.getElementById('btn');\nconst handler = () => {};\nel.addEventListener('click', handler);\n// FIX: remove listener before removing element\nel.removeEventListener('click', handler);"),
  ("Security","XSS & Injection","Tricky","Cross-site scripting and injection attacks","How do you prevent XSS in vanilla JS?","Never use innerHTML/dangerouslySetInnerHTML with user input. Use textContent for plain text. Sanitize with DOMPurify if HTML is needed. Set CSP headers.","// VULNERABLE\nelement.innerHTML = userInput;\n// SAFE\nelement.textContent = userInput;\n// If HTML is required (rich text)\nimport DOMPurify from 'dompurify';\nelement.innerHTML = DOMPurify.sanitize(userInput, {\n  ALLOWED_TAGS: ['b', 'i', 'em', 'strong', 'a'],\n  ALLOWED_ATTR: ['href'],\n});"),
  ("Security","CORS","Intermediate","Cross-Origin Resource Sharing — browser security policy","Does CORS protect your API from server-to-server requests?","No. CORS is a browser-enforced policy — browsers respect it, servers don't. A Node.js script or curl ignores CORS headers and can call your API freely. Real protection: auth tokens, rate limiting.","// Server (Express)\napp.use(cors({\n  origin: ['https://devquiz.app', 'http://localhost:5173'],\n  credentials: true, // allow cookies\n  methods: ['GET','POST','PUT','DELETE'],\n  allowedHeaders: ['Content-Type', 'Authorization'],\n}));\n// Preflight (OPTIONS) is handled automatically by cors()"),
  ("Async","Promise combinators","Advanced","all, allSettled, any, race","When do you use Promise.any vs Promise.race?","race: resolves/rejects with first settled (either fulfilled or rejected). any: resolves with first FULFILLED, ignores rejections, only rejects if ALL reject.","// Race: first settled wins (including errors)\nconst result = await Promise.race([fetch(primary), timeout(5000)]);\n\n// Any: first success wins, ignores failures\nconst fastest = await Promise.any([fetchFromCDN1(url), fetchFromCDN2(url)]);\n\n// All: all must succeed\nconst [user, posts] = await Promise.all([fetchUser(id), fetchPosts(id)]);\n\n// AllSettled: wait for all, get status of each\nconst results = await Promise.allSettled([p1, p2, p3]);"),
]

# ─── React extra ──────────────────────────────────────────────────────────────
REACT_EXTRA = [
  ("Testing","React Testing Library","Intermediate","Test components as users interact — not implementation","What is the guiding principle of RTL?","Test behaviour, not implementation. Query by accessible role/text/label (as a user would), not by class names or component internals. Encourages accessible code.","import { render, screen, fireEvent, waitFor } from '@testing-library/react';\ntest('submits form with user data', async () => {\n  render(<LoginForm onLogin={mockFn} />);\n  fireEvent.change(screen.getByLabelText('Email'), { target: { value: 'a@b.com' } });\n  fireEvent.change(screen.getByLabelText('Password'), { target: { value: 'pass' } });\n  fireEvent.click(screen.getByRole('button', { name: /sign in/i }));\n  await waitFor(() => expect(mockFn).toHaveBeenCalledWith('a@b.com', 'pass'));\n});"),
  ("Testing","Mocking in React tests","Intermediate","Mock API calls, modules, timers","How do you mock fetch in React tests?","Use global.fetch = jest.fn() or MSW (Mock Service Worker) — MSW intercepts at network level, works in both tests and browser.","// MSW setup\nimport { http, HttpResponse } from 'msw';\nimport { setupServer } from 'msw/node';\nconst server = setupServer(\n  http.get('/api/user', () => HttpResponse.json({ name: 'Alice' })),\n);\nbeforeAll(() => server.listen());\nafterEach(() => server.resetHandlers());\nafterAll(() => server.close());"),
  ("State","React Query / TanStack Query","Intermediate","Server state management: caching, refetching, mutations","What does staleTime control?","How long data is considered fresh. During staleTime, no refetch happens. After staleTime, data is 'stale' — still shown but refetched in background on window focus or remount.","import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';\nconst { data, isLoading } = useQuery({\n  queryKey: ['user', userId],\n  queryFn:  () => fetchUser(userId),\n  staleTime: 60_000, // fresh for 1 min\n  gcTime:    5 * 60_000, // removed from cache after 5 min\n});\nconst qc = useQueryClient();\nconst mut = useMutation({ mutationFn: updateUser, onSuccess: () => qc.invalidateQueries(['user']) });"),
  ("State","Jotai & Recoil","Advanced","Atomic state management","What is the advantage of atomic state over a single store?","Atoms are independent — components only subscribe to atoms they use. No need for selectors to prevent re-renders. Easy to derive state with computed atoms.","import { atom, useAtom } from 'jotai';\nconst countAtom  = atom(0);\nconst doubleAtom = atom(get => get(countAtom) * 2); // derived\n\nfunction Counter() {\n  const [count, setCount] = useAtom(countAtom);\n  const [double] = useAtom(doubleAtom);\n  return <button onClick={() => setCount(c => c + 1)}>{count} x2={double}</button>;\n}"),
  ("Forms","React Hook Form","Intermediate","Performant forms with minimal re-renders","Why is RHF faster than controlled inputs?","Uncontrolled by default — uses refs, not state. Only re-renders on actual errors or on submit. Formik re-renders on every keystroke (controlled inputs).","import { useForm } from 'react-hook-form';\nimport { zodResolver } from '@hookform/resolvers/zod';\nconst { register, handleSubmit, formState: { errors } } = useForm({\n  resolver: zodResolver(schema),\n});\n<form onSubmit={handleSubmit(onSubmit)}>\n  <input {...register('email')} />\n  {errors.email && <span>{errors.email.message}</span>}\n  <button type='submit'>Submit</button>\n</form>"),
  ("Patterns","useOptimistic (React 19)","Advanced","Optimistic UI updates during async transitions","What happens when the server call fails with useOptimistic?","The optimistic state is automatically reverted to the previous value. React handles the rollback when the action's Promise rejects.","import { useOptimistic, useTransition } from 'react';\nconst [optimisticLikes, addOptimisticLike] = useOptimistic(\n  likes,\n  (state, newLike) => [...state, newLike]\n);\nasync function handleLike() {\n  addOptimisticLike({ id: 'temp', userId }); // immediate UI update\n  await likePost(postId); // actual server call\n  // On failure: auto-reverts optimisticLikes\n}"),
  ("React 19","use() hook","Advanced","Read resources (Promises, Context) in render","What makes use() different from useContext and await?","use() can be called conditionally (unlike other hooks). Works with Promises — suspends the component until Promise resolves. Works with Context — same as useContext but callable anywhere.","import { use } from 'react';\n// Read context conditionally\nif (darkMode) {\n  const theme = use(ThemeContext); // OK -- use() is conditional-safe\n}\n// Unwrap promise (suspends until resolved)\nfunction UserProfile({ userPromise }) {\n  const user = use(userPromise); // suspends, then renders\n  return <div>{user.name}</div>;\n}"),
  ("Accessibility","React Accessibility","Intermediate","aria-* props, role, keyboard navigation, focus management","How do you implement a focus trap in a modal?","On modal open: save last focused element, move focus into modal. Intercept Tab/Shift+Tab to cycle through focusable elements inside modal. On close: restore focus to saved element.","function useFocusTrap(ref: RefObject<HTMLElement>, active: boolean) {\n  useEffect(() => {\n    if (!active) return;\n    const el = ref.current;\n    const focusable = el?.querySelectorAll('button,input,[tabindex]:not([tabindex=\"-1\"])');\n    const first = focusable?.[0] as HTMLElement;\n    const last  = focusable?.[focusable.length-1] as HTMLElement;\n    first?.focus();\n    const handleTab = (e: KeyboardEvent) => {\n      if (e.key !== 'Tab') return;\n      if (e.shiftKey ? document.activeElement === first : document.activeElement === last) {\n        e.preventDefault();\n        (e.shiftKey ? last : first).focus();\n      }\n    };\n    el?.addEventListener('keydown', handleTab);\n    return () => el?.removeEventListener('keydown', handleTab);\n  }, [active]);\n}"),
  ("Internals","Fiber architecture","Advanced","React's internal reconciliation engine","What problem did Fiber solve over the old stack reconciler?","Old reconciler: synchronous, recursive — once started, couldn't be interrupted. Fiber: work broken into units, interruptible, prioritizable. Enables concurrent features (useTransition, Suspense streaming).","// Fiber = linked list of work units\n// Each component = a fiber node with:\n// - type (function/class/element)\n// - key\n// - stateNode (DOM/class instance)\n// - child/sibling/return (tree pointers)\n// - pendingProps / memoizedProps\n// - pendingState\n// - effectTag (insert/update/delete)\n// Work loop can yield between fiber units"),
  ("Tricky","React 18 root API","Tricky","createRoot vs ReactDOM.render","Why must you use createRoot for React 18 features?","createRoot enables concurrent mode — all React 18 features (automatic batching, useTransition, Suspense streaming) require it. ReactDOM.render uses legacy mode — no concurrent features.","// React 18\nimport { createRoot } from 'react-dom/client';\nconst root = createRoot(document.getElementById('root'));\nroot.render(<App />);\n// Hydration (SSR)\nimport { hydrateRoot } from 'react-dom/client';\nconst root = hydrateRoot(document.getElementById('root'), <App />);"),
]

# ─── Next.js extra ────────────────────────────────────────────────────────────
NEXT_EXTRA = [
  ("Auth","NextAuth / Auth.js","Intermediate","Authentication framework for Next.js","How does Auth.js handle session storage?","By default: JWTs (stateless — no DB needed). Can switch to database sessions (Prisma/Drizzle adapter) for revoking sessions server-side. JWT session stored in HTTP-only cookie.","// app/api/auth/[...nextauth]/route.ts\nimport NextAuth from 'next-auth';\nimport GitHub from 'next-auth/providers/github';\nconst { handlers, auth } = NextAuth({\n  providers: [GitHub],\n  callbacks: {\n    session: ({ session, token }) => ({ ...session, userId: token.sub }),\n  },\n});\nexport const { GET, POST } = handlers;\n// In Server Component:\nconst session = await auth();"),
  ("Auth","Protecting routes","Intermediate","Middleware-based auth guards","How do you protect pages in App Router without a HOC?","Use middleware (edge runtime) to check token and redirect. For server components, call auth() at the top and redirect(). For client components, useSession() from next-auth/react.","// middleware.ts\nexport { auth as middleware } from '@/auth';\nexport const config = { matcher: ['/dashboard/:path*', '/api/user/:path*'] };\n// Server Component auth check\nimport { auth } from '@/auth';\nimport { redirect } from 'next/navigation';\nasync function DashboardPage() {\n  const session = await auth();\n  if (!session) redirect('/login');\n  return <Dashboard user={session.user} />;\n}"),
  ("Testing","Next.js Testing","Intermediate","Jest + React Testing Library for App Router","How do you test Server Components?","Server Components are async functions — render them and await. For components with fetch, mock global.fetch. Use next/jest config for transforms.","// jest.config.ts\nconst config = require('next/jest');\nmodule.exports = config({ dir: './' })({\n  testEnvironment: 'jsdom',\n});\n// Test Server Component\nit('renders posts', async () => {\n  global.fetch = jest.fn().mockResolvedValue({\n    ok: true, json: async () => [{ id: 1, title: 'Post' }]\n  });\n  const jsx = await PostsList();\n  const { getByText } = render(jsx);\n  expect(getByText('Post')).toBeTruthy();\n});"),
  ("Deployment","Vercel deployment","Basic","Deploying Next.js to Vercel","What is the difference between Vercel Edge and Serverless functions?","Serverless: full Node.js runtime, runs per-region, cold starts. Edge: V8 isolates, runs globally close to user, instant cold start, no Node.js APIs. Edge is faster for auth middleware and A/B testing; Serverless for DB queries.","// Use Edge runtime for fast middleware\nexport const runtime = 'edge'; // in route.ts or page.tsx\n// Vercel-specific features\n// ISR: fetch with revalidate\n// Edge Config: ultra-low-latency key-value\nimport { get } from '@vercel/edge-config';\nconst featureFlag = await get('enableNewUI');"),
  ("i18n","Internationalisation","Intermediate","Multiple language support in Next.js","How do you implement i18n in App Router?","Use locale-based routing: app/[locale]/layout.tsx. Detect preferred locale in middleware. next-intl or next-i18next libraries handle message loading and formatting.","// middleware.ts -- detect and redirect to locale\nimport { match } from '@formatjs/intl-localematcher';\nexport function middleware(req) {\n  const locale = match(acceptedLanguages, ['en','hi','es'], 'en');\n  req.nextUrl.pathname = `/${locale}${req.nextUrl.pathname}`;\n  return NextResponse.redirect(req.nextUrl);\n}\n// app/[locale]/layout.tsx\nexport default async function Layout({ children, params }) {\n  const { locale } = await params;\n  const messages = await import(`../../messages/${locale}.json`);\n  return <NextIntlClientProvider locale={locale} messages={messages.default}>{children}</NextIntlClientProvider>;\n}"),
  ("Error Handling","error.tsx & global-error.tsx","Intermediate","Error boundaries in App Router","What is the difference between error.tsx and global-error.tsx?","error.tsx: handles errors in the segment — layout still renders. global-error.tsx: handles errors in root layout — must include <html>/<body>, replaces entire page.","// app/dashboard/error.tsx\n'use client';\nexport default function Error({ error, reset }: { error: Error; reset: () => void }) {\n  return (\n    <div>\n      <h2>Dashboard error: {error.message}</h2>\n      <button onClick={reset}>Try again</button>\n    </div>\n  );\n}\n// app/global-error.tsx\n'use client';\nexport default function GlobalError({ error, reset }) {\n  return <html><body><h1>Fatal error</h1><button onClick={reset}>Reload</button></body></html>;\n}"),
  ("Security","Next.js Security headers","Advanced","Set security headers via next.config","What is Content-Security-Policy and why is it important?","CSP tells browser which sources are allowed for scripts, styles, images, etc. Prevents XSS — even if attacker injects a <script>, CSP blocks execution if src not whitelisted.","// next.config.ts\nconst securityHeaders = [\n  { key: 'X-Frame-Options', value: 'DENY' },\n  { key: 'X-Content-Type-Options', value: 'nosniff' },\n  { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },\n  { key: 'Content-Security-Policy',\n    value: \"default-src 'self'; script-src 'self' 'nonce-{nonce}'\" },\n];\nasync headers() { return [{ source: '/(.*)', headers: securityHeaders }]; }"),
  ("Performance","Bundle analysis","Intermediate","Analyse and reduce Next.js bundle size","How do you use @next/bundle-analyzer?","Install, wrap next.config with withBundleAnalyzer, set ANALYZE=true at build time. Opens a treemap of your client + server bundles — identify large dependencies.","npm i @next/bundle-analyzer\n// next.config.ts\nconst withAnalyzer = require('@next/bundle-analyzer')({\n  enabled: process.env.ANALYZE === 'true',\n});\nmodule.exports = withAnalyzer(nextConfig);\n// Run\nANALYZE=true npm run build"),
]

# ─── TypeScript extra ─────────────────────────────────────────────────────────
TS_EXTRA = [
  ("Types","Zod runtime validation","Intermediate","Schema validation that derives TypeScript types","How does Zod differ from TypeScript types?","TS types are compile-time only — erased at runtime. Zod validates at runtime AND infers TS types. Use for API responses, form data, env variables.","import { z } from 'zod';\nconst UserSchema = z.object({\n  id:    z.string().uuid(),\n  name:  z.string().min(1).max(100),\n  email: z.string().email(),\n  age:   z.number().int().min(0).optional(),\n});\ntype User = z.infer<typeof UserSchema>; // TS type from schema\nconst result = UserSchema.safeParse(apiResponse);\nif (result.success) { const user: User = result.data; }"),
  ("Types","Type narrowing patterns","Advanced","instanceof, typeof, in, discriminated unions, assertion functions","What is the in operator used for in TS narrowing?","'prop' in obj narrows to types that have that property. Works for distinguishing union members without a discriminant field.","function handleResponse(res: SuccessResponse | ErrorResponse) {\n  if ('data' in res) {\n    console.log(res.data); // SuccessResponse\n  } else {\n    console.error(res.error); // ErrorResponse\n  }\n}\n// instanceof narrowing\nfunction handle(e: unknown) {\n  if (e instanceof ValidationError) showValidation(e.fields);\n  else if (e instanceof NetworkError) showRetry();\n  else throw e;\n}"),
  ("Patterns","Builder pattern with types","Advanced","Fluent API for constructing complex objects type-safely","How do you enforce required fields at the type level with Builder?","Use phantom types — track which fields have been set as type parameters. The build() method is only available when all required types are set.","class QueryBuilder<TTable extends string = never, TFields extends string = never> {\n  #table = '';\n  #fields: string[] = [];\n  from<T extends string>(table: T): QueryBuilder<T, TFields> {\n    this.#table = table;\n    return this as any;\n  }\n  select<F extends string>(...fields: F[]): QueryBuilder<TTable, F> {\n    this.#fields = fields;\n    return this as any;\n  }\n  build(this: QueryBuilder<string, string>) {\n    return `SELECT ${this.#fields.join(',')} FROM ${this.#table}`;\n  }\n}\nnew QueryBuilder().from('users').select('id','name').build();"),
  ("Config","Path aliases","Basic","Resolve @/ imports to src/ directory","How do you set up path aliases in TS + Vite?","Two places: tsconfig.json paths (for TS type checking) and vite.config.ts resolve.alias (for bundler resolution). Both required.","// tsconfig.json\n{ \"compilerOptions\": { \"paths\": { \"@/*\": [\"./src/*\"] } } }\n// vite.config.ts\nimport path from 'path';\nexport default defineConfig({\n  resolve: { alias: { '@': path.resolve(__dirname, 'src') } },\n});\n// Usage\nimport { Button } from '@/components/Button';"),
  ("Types","Discriminated unions with exhaustive check","Tricky","Ensure all union cases are handled","Why combine discriminated unions with never?","TypeScript will error at the never assignment if a new union member is added and not handled in the switch. Automated exhaustiveness checking at compile time.","type Notification =\n  | { type: 'email'; to: string }\n  | { type: 'sms';   phone: string }\n  | { type: 'push';  deviceId: string };\nfunction send(n: Notification) {\n  switch (n.type) {\n    case 'email': sendEmail(n.to); break;\n    case 'sms':   sendSMS(n.phone); break;\n    case 'push':  sendPush(n.deviceId); break;\n    default:\n      const _: never = n; // compile error if new type added\n  }\n}"),
]

# ─── HTML extra ───────────────────────────────────────────────────────────────
HTML_EXTRA = [
  ("Semantics","time element","Basic","Machine-readable date/time with human text","Why use <time> instead of plain text for dates?","Machine-parseable datetime attribute enables calendar apps, search engines, screen readers, and microformats to extract dates reliably.","<time datetime='2024-12-25'>Christmas Day</time>\n<time datetime='2024-12-25T09:00:00Z'>Dec 25 at 9am UTC</time>"),
  ("Semantics","address element","Basic","Contact information for nearest article/body ancestor","Is <address> for postal addresses?","Not necessarily — it's for contact info of the author/owner of the nearest article or body. Physical address is one use case but also: email, phone, social.","<footer>\n  <address>\n    Written by <a href='mailto:author@dev.com'>Author</a>.\n    Visit at <a href='https://devquiz.app'>DevQuiz</a>.\n  </address>\n</footer>"),
  ("Semantics","srcset & sizes","Intermediate","Responsive images with multiple resolutions","What is the difference between srcset with w descriptors vs x descriptors?","w (width descriptor): browser picks based on layout size × device DPR. x (pixel density): only considers device DPR, not layout. Use w descriptors with sizes for full responsive control.","<img\n  src='img-400.jpg'\n  srcset='img-400.jpg 400w, img-800.jpg 800w, img-1200.jpg 1200w'\n  sizes='(max-width: 600px) 100vw, (max-width: 1200px) 50vw, 33vw'\n  alt='Responsive image'\n  loading='lazy'\n  decoding='async'\n>"),
  ("Performance","loading=lazy","Basic","Native browser lazy loading for images and iframes","Does loading=lazy work on all browsers?","Supported in all modern browsers (Chrome 76+, Firefox 75+, Safari 15.4+). Add a JS polyfill or use Intersection Observer for older Safari. Always set explicit width/height to prevent CLS.","<img src='photo.jpg' alt='...' loading='lazy' decoding='async'\n  width='800' height='600'>\n<iframe src='video-embed.html' loading='lazy'></iframe>"),
  ("Tricky","contenteditable pitfalls","Tricky","Browser differences in contenteditable behaviour","What HTML does Enter insert in contenteditable across browsers?","Chrome: <div>. Firefox: <br>. Safari: <br> or <div>. Use execCommand (deprecated) or intercept keydown and normalise. Better: use a rich text library (Tiptap, Slate, Quill).","// Normalise Enter to paragraph\nel.addEventListener('keydown', e => {\n  if (e.key === 'Enter') {\n    e.preventDefault();\n    document.execCommand('insertLineBreak'); // deprecated but works\n    // Or: insert a <p> programmatically\n  }\n});"),
]

# ─── CSS extra ────────────────────────────────────────────────────────────────
CSS_EXTRA = [
  ("Modern CSS","View Transitions API","Advanced","Animated page transitions with CSS — no JS framework","What is the View Transitions API?","Browser-native page transition animations. Capture before/after states, animate between them with CSS. Works for SPA navigation and (Chrome 126+) cross-document navigation.","// Trigger transition\ndocument.startViewTransition(() => {\n  updateDOM(); // synchronous DOM update\n});\n/* CSS */\n::view-transition-old(root) { animation: slide-out 0.3s ease; }\n::view-transition-new(root) { animation: slide-in 0.3s ease; }\n/* Named transitions */\n.hero { view-transition-name: hero; }"),
  ("Modern CSS","@layer with Tailwind","Advanced","Cascade layers for utility-first CSS control","How do you prevent Tailwind utilities from losing to component CSS?","Wrap base/component styles in lower-priority layers. Tailwind v4 uses @layer natively.","/* Ensure utilities always win */\n@layer base, components, utilities;\n@layer base { body { font-family: sans-serif; } }\n@layer components {\n  .btn { padding: 0.5rem 1rem; border-radius: 0.5rem; }\n}\n/* Tailwind utilities are in @layer utilities -- always override */"),
  ("Modern CSS","color-mix() & oklch","Advanced","Modern CSS color functions","Why use oklch over hsl?","oklch (lightness, chroma, hue) is perceptually uniform — same numeric lightness means same perceived brightness across hues. HSL is not perceptually uniform — blue at 50% L looks darker than yellow at 50% L.","  :root {\n  --primary: oklch(55% 0.2 264); /* indigo */\n  /* Generate tints automatically */\n  --primary-light: oklch(from var(--primary) calc(l + 20%) c h);\n  --primary-dark:  oklch(from var(--primary) calc(l - 20%) c h);\n}\n/* Mix colors */\n.overlay { background: color-mix(in oklch, #6366F1 70%, transparent); }"),
  ("Modern CSS","aspect-ratio","Basic","Maintain element proportions without padding hacks","What did we use before aspect-ratio?","Padding-top hack: padding-top: 56.25% (for 16:9) on a relative container with absolute positioned content. aspect-ratio eliminates this completely.","/* 16:9 video container */\n.video-wrapper { aspect-ratio: 16 / 9; width: 100%; }\n/* Square avatar */\n.avatar { width: 3rem; aspect-ratio: 1; border-radius: 50%; }\n/* Intrinsic if content taller */\n.card { aspect-ratio: 4 / 3 auto; }"),
  ("Modern CSS","CSS Anchoring","Advanced","Position elements relative to another element (CSS Anchor Positioning)","What problem does CSS Anchor Positioning solve?","Positioning tooltips/popovers relative to their trigger — previously required JS to calculate coordinates. Now purely declarative CSS.","/* Chrome 125+ */\n.trigger { anchor-name: --btn; }\n.tooltip {\n  position: absolute;\n  position-anchor: --btn;\n  bottom: calc(anchor(top) + 8px);\n  left: anchor(center);\n  transform: translateX(-50%);\n}"),
]
