JS_DATA = [
  # Loops
  ("Loops","for loop","Basic","Classic iteration with init, condition, increment","What is the difference between break and continue?","break exits the loop entirely. continue skips the current iteration and moves to the next. Both work in for, while, do-while, and for...of.","for (let i = 0; i < 5; i++) {\n  if (i === 2) continue; // skip 2\n  if (i === 4) break;    // stop at 4\n  console.log(i); // 0 1 3\n}"),
  ("Loops","for...of","Basic","Iterate over iterables: arrays, strings, Maps, Sets","What can you NOT iterate with for...of?","Plain objects — they are not iterable by default. Use for...in for keys, or Object.entries() with for...of. for...of works on anything with [Symbol.iterator].","for (const char of 'hello') console.log(char); // h e l l o\nfor (const [k, v] of new Map([['a',1]])) console.log(k, v);\nfor (const item of new Set([1,2,2,3])) console.log(item); // 1 2 3"),
  ("Loops","for...in","Tricky","Iterate over enumerable string keys of an object","Why is for...in dangerous on arrays?","It iterates prototype chain keys too, and key order isn't guaranteed for numeric indices in all engines. Use for...of or forEach for arrays.","const obj = { a: 1, b: 2 };\nfor (const key in obj) {\n  if (Object.hasOwn(obj, key)) // skip prototype props\n    console.log(key, obj[key]);\n}"),
  ("Loops","while & do-while","Basic","Condition-first vs body-first loops","When does do-while make more sense than while?","When the body must execute at least once — e.g., prompt user until valid input, game loop, retry logic.","let i = 0;\nwhile (i < 3) { console.log(i); i++; }\n\nlet input;\ndo {\n  input = getInput();\n} while (!isValid(input)); // always runs once"),
  ("Loops","forEach","Basic","Array method — iterate with callback","Does forEach respect return or break?","No. return inside forEach only exits the callback, not the loop. You cannot break out early. Use for...of if you need break/return, or .some() for early exit.","[1,2,3].forEach((n, index, arr) => {\n  console.log(n, index);\n  return; // only exits callback, loop continues\n});\n// Early exit trick\n[1,2,3].some(n => { console.log(n); return n === 2; }); // stops at 2"),

  # Switch
  ("Control Flow","switch statement","Basic","Multi-branch conditional on a single value","What is fall-through in switch?","Without break, execution continues into the next case. Intentional fall-through shares code between cases. Accidental fall-through is a common bug.","switch (status) {\n  case 'loading':\n  case 'pending': // fall-through -- same handler\n    showSpinner();\n    break;\n  case 'done':\n    showData();\n    break;\n  default:\n    showError();\n}"),
  ("Control Flow","Ternary operator","Basic","condition ? valueIfTrue : valueIfFalse","Can you nest ternaries?","Technically yes, but deeply nested ternaries are hard to read. Prefer if/else or early return for complex logic.","const role = isAdmin ? 'admin' : isEditor ? 'editor' : 'viewer';\n// Cleaner with if/else for > 2 branches"),
  ("Control Flow","try/catch/finally","Intermediate","Error handling in synchronous and async code","Does finally run even after return in try?","Yes. finally always runs — after try, catch, or even after return. The return value from finally overrides a return in try/catch.","async function load() {\n  try {\n    const data = await fetchData();\n    return data;\n  } catch (err) {\n    if (err instanceof NetworkError) retry();\n    else throw err; // re-throw unknown errors\n  } finally {\n    setLoading(false); // always runs\n  }\n}"),
  ("Control Flow","Optional chaining & nullish","Intermediate","?. and ?? for safe property access","What is the difference between ?. and ??","?. short-circuits if value is null/undefined (returns undefined). ?? provides fallback for null/undefined only. Combine them: obj?.value ?? 'default'.","const street = user?.address?.street ?? 'No address';\nconst len = str?.trim()?.length ?? 0;\n// Safe method call\nconst res = obj?.method?.() ?? [];"),

  # Array methods deep
  ("Arrays","map","Basic","Transform each element, return new array","Does map skip empty slots in sparse arrays?","Yes. map, filter, reduce skip holes (empty slots) in sparse arrays. forEach also skips them. Array.from does not — fills with undefined.","const nums = [1, 2, 3];\nconst doubled = nums.map(n => n * 2); // [2, 4, 6]\n// With index\nconst indexed = nums.map((n, i) => ({ index: i, value: n }));"),
  ("Arrays","filter","Basic","Keep elements passing predicate, return new array","What does filter return if nothing matches?","Empty array [] — never null or undefined. Safe to chain.","const evens = [1,2,3,4].filter(n => n % 2 === 0); // [2,4]\nconst active = users.filter(u => u.active && u.role === 'admin');"),
  ("Arrays","reduce","Intermediate","Accumulate array into single value","What happens if you call reduce on empty array without initial value?","TypeError: Reduce of empty array with no initial value. Always provide an initial value for safety.","const sum = [1,2,3].reduce((acc, n) => acc + n, 0); // 6\n// Group by\nconst grouped = users.reduce((acc, u) => {\n  (acc[u.role] ??= []).push(u);\n  return acc;\n}, {});"),
  ("Arrays","find & findIndex","Basic","Find first matching element/index","What does find return if nothing matches?","undefined. findIndex returns -1. Different from filter which returns [].","const user = users.find(u => u.id === 42); // or undefined\nconst idx = users.findIndex(u => u.id === 42); // or -1\nconst found = users.findLast(u => u.active); // from end (ES2023)"),
  ("Arrays","some & every","Basic","Check if any/all elements match predicate","Does some or every mutate the array?","No. Both return boolean and stop early — some stops at first true, every stops at first false.","const hasAdmin = users.some(u => u.role === 'admin');\nconst allActive = users.every(u => u.active);\n// Equivalent: !users.some(u => !u.active)"),
  ("Arrays","flat & flatMap","Intermediate","Flatten nested arrays","What is the depth parameter in flat()?","Number of levels to flatten. flat() defaults to 1. flat(Infinity) fully flattens.","[[1,2],[3,[4,5]]].flat();    // [1,2,3,[4,5]]\n[[1,2],[3,[4,5]]].flat(2);   // [1,2,3,4,5]\n// flatMap = map then flat(1)\n[1,2,3].flatMap(n => [n, n*2]); // [1,2,2,4,3,6]"),
  ("Arrays","sort","Tricky","Sort array in-place","What is the default sort order and its pitfall?","Default sort converts elements to strings and sorts lexicographically. [10,9,2].sort() = [10,2,9]! Always provide a comparator for numbers.","// WRONG: lexicographic\n[10, 2, 9].sort(); // [10, 2, 9]\n// CORRECT: numeric\n[10, 2, 9].sort((a, b) => a - b); // [2, 9, 10]\n// Stable sort (guaranteed ES2019+)\nusers.sort((a, b) => a.name.localeCompare(b.name));"),
  ("Arrays","splice vs slice","Tricky","Mutating vs non-mutating array operations","Which one mutates the original array?","splice mutates in-place (returns removed elements). slice returns new array without mutating.","const arr = [1,2,3,4,5];\narr.splice(1, 2);       // removes 2 elements at index 1; arr = [1,4,5]\narr.splice(1, 0, 'a');  // insert 'a' at index 1\nconst copy = arr.slice(1, 3); // [4,5] -- no mutation"),
  ("Arrays","Array.from & Array.of","Intermediate","Create arrays from iterables and arguments","How do you create an array of N items?","Array.from({length: N}, (_, i) => i) creates [0,1,...,N-1]. Array(N).fill(0) creates N zeros. Never use new Array(N) for values — creates sparse array.","Array.from('hello');           // ['h','e','l','l','o']\nArray.from({length:5},(_,i)=>i); // [0,1,2,3,4]\nArray.from(new Set([1,2,2]));  // [1,2]\nArray.of(1,2,3);               // [1,2,3]"),
  ("Arrays","includes vs indexOf","Basic","Check membership","Why use includes instead of indexOf for NaN?","indexOf uses strict equality — can't find NaN (NaN !== NaN). includes uses SameValueZero — correctly finds NaN.","[1,NaN,3].includes(NaN);    // true\n[1,NaN,3].indexOf(NaN);     // -1 (bug!)\n[1,2,3].includes(2);         // true\n[1,2,3].indexOf(2);          // 1 (index)"),

  # Objects deep
  ("Objects","Object methods","Basic","Create, assign, freeze, keys","What is Object.freeze vs Object.seal?","freeze: no add, no delete, no modify. seal: no add, no delete, but CAN modify existing values. Both are shallow — nested objects are not frozen/sealed.","const cfg = Object.freeze({ db: 'mongo', port: 27017 });\ncfg.port = 9999; // silently ignored (TypeError in strict mode)\n\nconst obj = Object.seal({ x: 1 });\nobj.x = 2;   // allowed\nobj.y = 3;   // silently ignored"),
  ("Objects","Getters & Setters","Intermediate","Computed properties with get/set","When would you use a getter instead of a method?","Getters look like properties — good for computed values derived from other properties (fullName from firstName+lastName). Setters add validation on assignment.","const user = {\n  _name: 'Alice',\n  get name() { return this._name.toUpperCase(); },\n  set name(v) {\n    if (typeof v !== 'string') throw TypeError();\n    this._name = v.trim();\n  }\n};\nuser.name; // 'ALICE'\nuser.name = ' Bob '; // trimmed to 'Bob'"),
  ("Objects","Destructuring","Intermediate","Extract values from objects/arrays","How do you rename during destructuring?","Use colon: { oldName: newName } = obj. Combine with default: { name: displayName = 'Guest' } = user.","const { name: displayName = 'Guest', age = 0 } = user;\nconst [first, , third, ...rest] = arr;\n// Nested\nconst { address: { city, zip } } = user;\n// Function params\nfunction draw({ x = 0, y = 0, color = 'black' } = {}) {}"),
  ("Objects","Spread & Rest","Basic","... operator for expand and collect","Does spread copy prototype methods?","No. Spread only copies own enumerable properties. Class instances lose their methods when spread into plain object.","const merged = { ...defaults, ...overrides };\nconst clone = { ...original }; // shallow copy\nfunction sum(...nums) { return nums.reduce((a,n) => a+n, 0); }\nsum(1, 2, 3, 4); // 10"),
  ("Objects","Classes","Intermediate","ES6 class syntax over prototype","Are class bodies in strict mode?","Yes, always. class body is always strict mode regardless of 'use strict'. Also: class declarations are NOT hoisted like function declarations (TDZ applies).","class Animal {\n  #name; // private field\n  constructor(name) { this.#name = name; }\n  get name() { return this.#name; }\n  speak() { return `${this.#name} makes a sound`; }\n  static create(name) { return new Animal(name); }\n}\nclass Dog extends Animal {\n  speak() { return super.speak() + ' (woof)'; }\n}"),
  ("Objects","Private class fields","Advanced","# prefix fields only accessible inside class body","Can you check if an object has a private field?","Use #field in obj (ergonomic brand check, ES2022). Returns true if obj is an instance with that private field.","class Circle {\n  #radius;\n  constructor(r) { this.#radius = r; }\n  get area() { return Math.PI * this.#radius ** 2; }\n  static isCircle(obj) { return #radius in obj; }\n}\nCircle.isCircle(new Circle(5)); // true"),

  # Functions
  ("Functions","call, apply, bind","Intermediate","Explicitly set 'this' context","What is the difference between call and apply?","call passes arguments individually. apply passes as array. bind returns new function with 'this' bound — doesn't call immediately.","function greet(greeting, punct) {\n  return `${greeting}, ${this.name}${punct}`;\n}\nconst user = { name: 'Alice' };\ngreet.call(user, 'Hello', '!');   // call: individual args\ngreet.apply(user, ['Hi', '?']);    // apply: array args\nconst hi = greet.bind(user, 'Hi'); // bind: partial application\nhi('!'); // 'Hi, Alice!'"),
  ("Functions","IIFE","Basic","Immediately Invoked Function Expression — creates isolated scope","Why are IIFEs less common in modern JS?","ES modules have their own scope — no need for IIFE to avoid polluting global. Still useful for async in top-level environments without module support.","(function() {\n  var private = 'not global';\n})();\n// Arrow IIFE\n(() => {\n  const data = init();\n  render(data);\n})();\n// Async IIFE\n(async () => {\n  const data = await fetchData();\n})();"),
  ("Functions","Currying","Advanced","Transform f(a,b,c) into f(a)(b)(c)","What is partial application vs currying?","Partial application: fix some arguments, return function needing the rest. Currying: each call takes exactly one argument. Related but distinct.","const curry = fn => {\n  const arity = fn.length;\n  return function curried(...args) {\n    if (args.length >= arity) return fn(...args);\n    return (...more) => curried(...args, ...more);\n  };\n};\nconst add = curry((a, b, c) => a + b + c);\nadd(1)(2)(3); // 6\nadd(1, 2)(3); // 6"),
  ("Functions","Debounce & Throttle","Advanced","Limit rate of function calls","What is the difference between debounce and throttle?","Debounce: waits for pause in calls, fires once after (search input). Throttle: fires at most once per interval regardless of how many calls (scroll handler).","function debounce(fn, ms) {\n  let timer;\n  return (...args) => {\n    clearTimeout(timer);\n    timer = setTimeout(() => fn(...args), ms);\n  };\n}\nfunction throttle(fn, ms) {\n  let last = 0;\n  return (...args) => {\n    const now = Date.now();\n    if (now - last >= ms) { last = now; fn(...args); }\n  };\n}"),
  ("Functions","Memoization","Advanced","Cache function results by input","When does memoization cause bugs?","When function has side effects or depends on external state. The cache returns old value even if external state changed.","function memoize(fn) {\n  const cache = new Map();\n  return function(...args) {\n    const key = JSON.stringify(args);\n    if (cache.has(key)) return cache.get(key);\n    const result = fn.apply(this, args);\n    cache.set(key, result);\n    return result;\n  };\n}\nconst fib = memoize(n => n <= 1 ? n : fib(n-1) + fib(n-2));"),

  # String methods
  ("Strings","String methods","Basic","Common built-in string operations","Does slice work on negative indices?","Yes. Negative indices count from the end. substr is deprecated — use slice or substring.","'hello world'.includes('world');  // true\n'hello'.startsWith('hel');        // true\n'  hi  '.trim();                  // 'hi'\n'a,b,c'.split(',');               // ['a','b','c']\n'hello'.slice(-3);                // 'llo'\n'ha'.repeat(3);                   // 'hahaha'\n'abc'.padStart(5, '0');           // '00abc'"),
  ("Strings","Template literals","Basic","Backtick strings with interpolation and multi-line","What are tagged template literals?","A function called with parts of a template literal. Used by libraries like styled-components, graphql, sql for safe interpolation.","const name = 'World';\n`Hello ${name}!`; // interpolation\n// Multi-line\nconst html = `\n  <div>\n    <p>${content}</p>\n  </div>\n`;\n// Tagged template\nfunction sql(strings, ...values) {\n  return strings.reduce((q, s, i) => q + s + (values[i] ?? ''), '');\n}\nsql`SELECT * FROM users WHERE id = ${userId}`;"),
  ("Strings","Regular Expressions","Intermediate","Pattern matching with RegExp","What is the difference between test and match?","RegExp.test(str) returns boolean. String.match(regex) returns array of matches or null. Use /g flag for all matches.","const emailRe = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;\nemailRe.test('a@b.com'); // true\n\n'hello world'.match(/\\w+/g); // ['hello', 'world']\n'foo bar baz'.replace(/\\b\\w/g, c => c.toUpperCase()); // 'Foo Bar Baz'\n// Named groups\nconst { year, month } = '2024-01'.match(/(?<year>\\d{4})-(?<month>\\d{2})/).groups;"),

  # Data structures
  ("Data Structures","Map","Intermediate","Key-value pairs with any key type","When to use Map over plain object?","Map: any key type (objects, functions), maintains insertion order, has .size, no prototype pollution, better performance for frequent add/delete.","const map = new Map();\nmap.set('key', 'value');\nmap.set({id:1}, 'obj key'); // objects as keys!\nmap.get('key');    // 'value'\nmap.has('key');    // true\nmap.size;          // 2\n// Iterate\nfor (const [k, v] of map) console.log(k, v);"),
  ("Data Structures","Set","Intermediate","Collection of unique values","How do you find the intersection of two Sets?","Use filter + has: [...setA].filter(x => setB.has(x)). ES2025 adds Set.prototype.intersection() natively.","const set = new Set([1, 2, 2, 3]); // {1, 2, 3}\nset.add(4); set.delete(2);\nset.has(3); // true\nset.size;   // 3\n// Remove duplicates from array\nconst unique = [...new Set(arr)];\n// Union\nconst union = new Set([...setA, ...setB]);"),
  ("Data Structures","WeakMap & WeakSet","Advanced","Weak references — entries garbage-collected when key unreachable","When would you use WeakMap?","Storing private data per object instance without preventing GC. Caching computed results per DOM node. Cannot be iterated — no memory leak risk.","const metadata = new WeakMap();\nfunction process(obj) {\n  if (metadata.has(obj)) return metadata.get(obj);\n  const result = expensiveCompute(obj);\n  metadata.set(obj, result);\n  return result;\n}\n// When obj is garbage collected, entry is removed automatically"),
  ("Data Structures","Symbol","Advanced","Unique, immutable primitive values","What are well-known Symbols used for?","Customize built-in JS behaviour: Symbol.iterator makes object iterable, Symbol.toPrimitive controls coercion, Symbol.hasInstance controls instanceof.","const id = Symbol('id');\nconst id2 = Symbol('id');\nid === id2; // false -- always unique\n// Well-known Symbol\nclass Range {\n  constructor(from, to) { this.from = from; this.to = to; }\n  [Symbol.iterator]() {\n    let cur = this.from;\n    return { next: () => cur <= this.to ? { value: cur++, done: false } : { done: true } };\n  }\n}\n[...new Range(1,4)]; // [1,2,3,4]"),

  # DOM & Browser
  ("Browser","Event handling","Intermediate","addEventListener, event delegation","What is event delegation and why use it?","Attach one listener to parent instead of many to children. Handles dynamically added elements. Memory efficient for lists.","// Instead of one listener per item:\ndocument.querySelector('#list').addEventListener('click', e => {\n  const item = e.target.closest('li');\n  if (!item) return;\n  console.log(item.dataset.id);\n});\n// e.stopPropagation() -- stop bubbling\n// e.preventDefault() -- prevent default action"),
  ("Browser","Fetch API","Intermediate","Modern HTTP requests","Does fetch reject on 4xx/5xx responses?","No! fetch only rejects on network failure. A 404 or 500 resolves with ok:false. Always check res.ok or res.status.","async function fetchUser(id) {\n  const res = await fetch(`/api/users/${id}`, {\n    method: 'GET',\n    headers: { 'Content-Type': 'application/json',\n               'Authorization': `Bearer ${token}` }\n  });\n  if (!res.ok) throw new Error(`HTTP ${res.status}`);\n  return res.json();\n}"),
  ("Browser","localStorage & sessionStorage","Basic","Browser key-value storage","What is the difference between localStorage and sessionStorage?","localStorage persists until explicitly cleared. sessionStorage cleared when tab closes. Both: 5-10MB, string values only, synchronous (can block UI).","localStorage.setItem('key', JSON.stringify(obj));\nconst data = JSON.parse(localStorage.getItem('key'));\nlocalStorage.removeItem('key');\nlocalStorage.clear();\n// sessionStorage: same API but tab-scoped\nsessionStorage.setItem('temp', 'value');"),
  ("Browser","IntersectionObserver","Advanced","Observe when element enters/exits viewport","What is IntersectionObserver used for?","Lazy loading images, infinite scroll, analytics (element viewed), triggering animations on scroll — without scroll event listeners (which cause jank).","const observer = new IntersectionObserver((entries) => {\n  entries.forEach(entry => {\n    if (entry.isIntersecting) {\n      entry.target.src = entry.target.dataset.src; // lazy load\n      observer.unobserve(entry.target);\n    }\n  });\n}, { threshold: 0.1 });\ndocument.querySelectorAll('img[data-src]').forEach(img => observer.observe(img));"),
  ("Browser","MutationObserver","Advanced","Watch DOM for changes","When do you need MutationObserver?","Third-party widgets injecting content, monitoring dynamic content for accessibility, implementing undo for DOM changes.","const observer = new MutationObserver(mutations => {\n  mutations.forEach(m => {\n    m.addedNodes.forEach(node => console.log('Added:', node));\n  });\n});\nobserver.observe(document.body, {\n  childList: true,\n  subtree: true,\n  attributes: true\n});\nobserver.disconnect(); // stop observing"),

  # JSON & Date
  ("Utilities","JSON","Basic","Serialize/deserialize JavaScript values","What values does JSON.stringify lose?","undefined, functions, and Symbols are omitted from objects and become null in arrays. Use replacer parameter to handle them.","JSON.stringify({ a: 1, b: undefined, c: () => {} }); // '{\"a\":1}'\nJSON.stringify([1, undefined, 3]);                    // '[1,null,3]'\n// Pretty print\nJSON.stringify(obj, null, 2);\n// Replacer\nJSON.stringify(obj, (key, val) => val instanceof Date ? val.toISOString() : val);"),
  ("Utilities","Date","Basic","Built-in date/time handling","Why is Date.parse unreliable?","Date string parsing is implementation-dependent for formats other than ISO 8601. 'Jan 1 2024' may differ across browsers. Always use ISO 8601 (YYYY-MM-DD) or a library like date-fns.","const now = new Date();\nnow.toISOString();        // '2024-01-15T10:30:00.000Z'\nDate.now();               // milliseconds since epoch\nnew Date(2024, 0, 15);   // Jan 15 2024 (month is 0-indexed!)\nconst diff = dateB - dateA; // milliseconds"),
  ("Utilities","Math","Basic","Mathematical functions","What is the difference between Math.round, floor, ceil, and trunc?","round: nearest integer (0.5 rounds up). floor: always down. ceil: always up. trunc: removes decimal (toward zero — different from floor for negatives).","Math.round(4.5);  // 5\nMath.round(-4.5); // -4 (rounds toward +infinity)\nMath.floor(-4.1); // -5\nMath.trunc(-4.9); // -4 (just removes decimal)\nMath.max(...arr); // spread for array\nMath.random();    // [0, 1)\n(Math.random() * (max-min) + min) | 0; // random int"),

  # Error handling
  ("Error Handling","Error types","Intermediate","TypeError, RangeError, ReferenceError, SyntaxError, URIError","When should you create custom Error classes?","When callers need to distinguish your error from generic ones programmatically — catch (e) { if (e instanceof ValidationError) ... }. Include extra fields for context.","class AppError extends Error {\n  constructor(message, statusCode, code) {\n    super(message);\n    this.name = 'AppError';\n    this.statusCode = statusCode;\n    this.code = code;\n  }\n}\ntry {\n  throw new AppError('Not found', 404, 'USER_NOT_FOUND');\n} catch (e) {\n  if (e instanceof AppError) console.log(e.statusCode);\n  else throw e; // re-throw unknown errors\n}"),
]
